In [ ]:
from src.mta_graph import SubwayGraph
from src.complexes import ComplexesData
import pandas as pd

complexes = ComplexesData()
mta = SubwayGraph()

In [2]:
mta.build_graph()

In [ ]:
def get_onboards_data(complex_id: str, year: int = 2025, month: int = 9, day_of_week: str = "Monday", hour_of_day: str = "10"):
    from src.socrata_od_client import get_ridership_data

    # Get weekday ridership for May 2024 at 9am from station 623
    df = get_ridership_data(
        year=year,
        month=month,
        day_of_week=day_of_week,
        hour_of_day=hour_of_day,
        origin_station_complex_id=complex_id
    )

    df_ = df.sort_values('estimated_average_ridership', ascending=False)
    return df_

df_onboards_120 = get_onboards_data("120")
df_onboards_120

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
85,2025,9,Monday,10,120,Bedford Av (L),602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",130.6930
33,2025,9,Monday,10,120,Bedford Av (L),618,"14 St (A,C,E)/8 Av (L)",70.8448
167,2025,9,Monday,10,120,Bedford Av (L),601,"14 St (F,M,1,2,3)/6 Av (L)",43.5630
156,2025,9,Monday,10,120,Bedford Av (L),119,1 Av (L),42.7778
112,2025,9,Monday,10,120,Bedford Av (L),610,"Grand Central-42 St (S,4,5,6,7)",41.5626
...,...,...,...,...,...,...,...,...,...
198,2025,9,Monday,10,120,Bedford Av (L),421,"Gun Hill Rd (2,5)",0.2224
86,2025,9,Monday,10,120,Bedford Av (L),5,"36 Av (N,W)",0.2206
196,2025,9,Monday,10,120,Bedford Av (L),30,Prospect Av (R),0.2206
206,2025,9,Monday,10,120,Bedford Av (L),48,Avenue H (Q),0.2206
113,2025,9,Monday,10,120,Bedford Av (L),282,21 St (G),0.2206

In [4]:
# 0 = north/east-bound, 1 = south/west-bound
def get_ordered_stops(line : str, direction: int, return_type : int = 0):
    complex_ids = [int(complexes.get_complex_id_by_gtfs_stop_id(stop[:-1])) for stop in mta.ordered_stops(line, direction)]
    complex_names = [complexes.get_station_name_by_gtfs_id(stop[:-1]) for stop in mta.ordered_stops(line, direction)]
    if return_type == 0:
        return dict(zip(complex_names, complex_ids))
    elif return_type == 1:
        return complex_ids
    else:
        return complex_names

get_ordered_stops("L", 0, 0)

{'Canarsie-Rockaway Pkwy': 138,
 'East 105 St': 137,
 'New Lots Av': 136,
 'Livonia Av': 135,
 'Sutter Av': 134,
 'Atlantic Av': 133,
 'Broadway Junction': 621,
 'Bushwick Av-Aberdeen St': 131,
 'Wilson Av': 130,
 'Halsey St': 129,
 'Myrtle-Wyckoff Avs': 630,
 'DeKalb Av': 127,
 'Jefferson St': 126,
 'Morgan Av': 125,
 'Montrose Av': 124,
 'Grand St': 123,
 'Graham Av': 122,
 'Lorimer St': 629,
 'Bedford Av': 120,
 '1 Av': 119,
 '3 Av': 118,
 '14 St-Union Sq': 602,
 '6 Av': 601,
 '8 Av': 618}

In [5]:
# 0 = north/east-bound, 1 = south/west-bound
def get_onboardings(origin_complex_id: str, line: str, direction: int, df_ : any):
    onboardings = 0
    boardings_df = pd.DataFrame(columns=df_.columns)
    stops_on_line = get_ordered_stops(line, direction, 1)
    stops_after = stops_on_line[stops_on_line.index(int(origin_complex_id)) + 1:]

    for i in range(len(df_)):
        print()
        destination_complex_id = str(df_.iloc[i]["destination_station_complex_id"])
        connecting_lines = mta.connecting_lines(origin_complex_id, destination_complex_id)
        
        print(f"Destination complex id: {destination_complex_id}")
        print(f"Connecting lines: {connecting_lines}")

        if len(connecting_lines) > 0: # Direct Connection Exists
            if line in connecting_lines:
                print(f"Stops after stop {origin_complex_id}: {stops_after}")

                if int(destination_complex_id) in stops_after:
                    print(f"{destination_complex_id} is in {stops_after}")
                    onboardings += df_.iloc[i]["estimated_average_ridership"] / len(connecting_lines)
                    df_tmp = df_.iloc[[i]].copy()
                    df_tmp["estimated_average_ridership"] /= len(connecting_lines)
                    boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)
                else:
                    print(f"{destination_complex_id} is not in stops_after")

        else: # Transfer Required
            shortest_paths = mta.all_shortest_paths(origin_complex_id, destination_complex_id)
            print(f"From {origin_complex_id} to {destination_complex_id}, shortest paths: {shortest_paths}")

            total_paths = 0
            num_paths = 0
            distances = {}
            for path in shortest_paths:
                connections = mta.connecting_lines(path[0], path[1])

                # total_distance = 0
                # all_connections = []
                # for j in range(len(path) - 1):
                #     connecting_line = mta.connecting_lines(path[j], path[j+1])[0]
                #     stops = get_ordered_stops(connecting_line, direction, 1)
                #     path_distance = abs(stops.index(int(path[j])) - stops.index(int(path[j+1])))
                #     all_connections += connecting_line
                #     total_distance += path_distance
                # distances[str(path)] = total_distance
                # print("Path: ", path, ", Total distance: ", total_distance, ", Connections: ", all_connections)
                # distance = abs(stops_on_line.index(int(path[0])) - stops_on_line.index(int(path[1])))
                # print(f"From {path[0]} to {path[1]}, connections: {connections}, distance: {distance}")
                total_paths += len(connections)
                if line in connections:
                    if int(path[1]) in stops_after:
                        num_paths += 1
            print(f"Total paths: {total_paths}, num paths: {num_paths}")
            print(i)
            if total_paths > 0 and num_paths > 0:
                onboardings += df_.iloc[i]["estimated_average_ridership"] * (num_paths / total_paths)
                df_tmp = df_.iloc[[i]].copy()
                df_tmp["estimated_average_ridership"] *= (num_paths / total_paths)
                print("df_tmp: ", df_tmp["destination_station_complex_id"])
                boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)

    return onboardings, boardings_df

In [6]:
df_onboards_120["estimated_average_ridership"].sum() # number of people who boarded the L train at Bedford Av at 9 am on Tuesday in Febuary 2025.

np.float64(1059.9913999999999)

In [7]:
# 0 = north/east-bound, 1 = south/west-bound
obs, df = get_onboardings ("120", "L", 0, df_onboards_120)

print("Onboardings: ", obs)
df

Destination complex id: 602
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
602 is in [119, 118, 602, 601, 618]

Destination complex id: 618
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
618 is in [119, 118, 602, 601, 618]

Destination complex id: 601
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
601 is in [119, 118, 602, 601, 618]

Destination complex id: 119
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
119 is in [119, 118, 602, 601, 618]

Destination complex id: 610
Connecting lines: []
From 120 to 610, shortest paths: [['120', '602', '610']]
Total paths: 1, num paths: 1
4
df_tmp:  112    610
Name: destination_station_complex_id, dtype: int64

Destination complex id: 164
Connecting lines: []
From 120 to 164, shortest paths: [['120', '618', '164'], ['120', '621', '164']]
Total paths: 2, num paths: 1
5
df_tmp:  219    164
Name: destination_station_complex_id, dtype: int64

Destination complex id: 611
Connecting lines: []
From 120 to 611, shortest paths: [['120', '602', '611'], ['120', '601', '611'], ['120', '618', '611'], ['120', '621', '611']]
Total paths: 4, num paths: 3
6
df_tmp:  131    611
Name: destination_station_complex_id, dtype: int64

Destination complex id: 607
Connecting lines: []
From 120 to 607, shortest paths: [['120', '602', '607'], ['120', '601', '607']]
Total paths: 2, num paths: 2
7
df_tmp:  256    607
Name: destination_station_complex_id, dtype: int64

Destination complex id: 225
Connecting lines: []
From 120 to 225, shortest paths: [['120', '601', '225']]
Total paths: 1, num paths: 1
8
df_tmp:  129    225
Name: destination_station_complex_id, dtype: int64

Destination complex id: 118
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
118 is in [119, 118, 602, 601, 618]

Destination complex id: 609
Connecting lines: []
From 120 to 609, shortest paths: [['120', '601', '609']]
Total paths: 1, num paths: 1
10
df_tmp:  244    609
Name: destination_station_complex_id, dtype: int64

Destination complex id: 623
Connecting lines: []
From 120 to 623, shortest paths: [['120', '602', '623'], ['120', '621', '623']]
Total paths: 2, num paths: 1
11
df_tmp:  217    623
Name: destination_station_complex_id, dtype: int64

Destination complex id: 619
Connecting lines: []
From 120 to 619, shortest paths: [['120', '602', '619'], ['120', '601', '619']]
Total paths: 2, num paths: 2
12
df_tmp:  55    619
Name: destination_station_complex_id, dtype: int64

Destination complex id: 17
Connecting lines: []
From 120 to 17, shortest paths: [['120', '602', '17']]
Total paths: 1, num paths: 1
13
df_tmp:  138    17
Name: destination_station_complex_id, dtype: int64

Destination complex id: 628
Connecting lines: []
From 120 to 628, shortest paths: [['120', '602', '628'], ['120', '601', '628'], ['120', '618', '628'], ['120', '621', '628']]
Total paths: 4, num paths: 3
14
df_tmp:  213    628
Name: destination_station_complex_id, dtype: int64

Destination complex id: 228
Connecting lines: []
From 120 to 228, shortest paths: [['120', '601', '228']]
Total paths: 1, num paths: 1
15
df_tmp:  166    228
Name: destination_station_complex_id, dtype: int64

Destination complex id: 614
Connecting lines: []
From 120 to 614, shortest paths: [['120', '601', '614'], ['120', '618', '614'], ['120', '621', '614']]
Total paths: 3, num paths: 2
16
df_tmp:  110    614
Name: destination_station_complex_id, dtype: int64

Destination complex id: 9
Connecting lines: []
From 120 to 9, shortest paths: [['120', '602', '9']]
Total paths: 1, num paths: 1
17
df_tmp:  142    9
Name: destination_station_complex_id, dtype: int64

Destination complex id: 612
Connecting lines: []
From 120 to 612, shortest paths: [['120', '602', '612'], ['120', '618', '612']]
Total paths: 2, num paths: 2
18
df_tmp:  38    612
Name: destination_station_complex_id, dtype: int64

Destination complex id: 405
Connecting lines: []
From 120 to 405, shortest paths: [['120', '602', '405']]
Total paths: 1, num paths: 1
19
df_tmp:  93    405
Name: destination_station_complex_id, dtype: int64

Destination complex id: 613
Connecting lines: []
From 120 to 613, shortest paths: [['120', '602', '613']]
Total paths: 1, num paths: 1
20
df_tmp:  76    613
Name: destination_station_complex_id, dtype: int64

Destination complex id: 13
Connecting lines: []
From 120 to 13, shortest paths: [['120', '602', '13']]
Total paths: 1, num paths: 1
21
df_tmp:  36    13
Name: destination_station_complex_id, dtype: int64

Destination complex id: 126
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
126 is not in stops_after

Destination complex id: 397
Connecting lines: []
From 120 to 397, shortest paths: [['120', '602', '397']]
Total paths: 1, num paths: 1
23
df_tmp:  22    397
Name: destination_station_complex_id, dtype: int64

Destination complex id: 10
Connecting lines: []
From 120 to 10, shortest paths: [['120', '602', '10']]
Total paths: 1, num paths: 1
24
df_tmp:  17    10
Name: destination_station_complex_id, dtype: int64

Destination complex id: 630
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
630 is not in stops_after

Destination complex id: 167
Connecting lines: []
From 120 to 167, shortest paths: [['120', '601', '167'], ['120', '618', '167'], ['120', '621', '167']]
Total paths: 3, num paths: 2
26
df_tmp:  47    167
Name: destination_station_complex_id, dtype: int64

Destination complex id: 16
Connecting lines: []
From 120 to 16, shortest paths: [['120', '602', '16']]
Total paths: 1, num paths: 1
27
df_tmp:  130    16
Name: destination_station_complex_id, dtype: int64

Destination complex id: 168
Connecting lines: []
From 120 to 168, shortest paths: [['120', '618', '168'], ['120', '621', '168']]
Total paths: 2, num paths: 1
28
df_tmp:  79    168
Name: destination_station_complex_id, dtype: int64

Destination complex id: 124
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
124 is not in stops_after

Destination complex id: 14
Connecting lines: []
From 120 to 14, shortest paths: [['120', '602', '14']]
Total paths: 1, num paths: 1
30
df_tmp:  63    14
Name: destination_station_complex_id, dtype: int64

Destination complex id: 127
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
127 is not in stops_after

Destination complex id: 125
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
125 is not in stops_after

Destination complex id: 409
Connecting lines: []
From 120 to 409, shortest paths: [['120', '602', '409']]
Total paths: 1, num paths: 1
33
df_tmp:  87    409
Name: destination_station_complex_id, dtype: int64

Destination complex id: 324
Connecting lines: []
From 120 to 324, shortest paths: [['120', '601', '324']]
Total paths: 1, num paths: 1
34
df_tmp:  207    324
Name: destination_station_complex_id, dtype: int64

Destination complex id: 403
Connecting lines: []
From 120 to 403, shortest paths: [['120', '602', '403']]
Total paths: 1, num paths: 1
35
df_tmp:  15    403
Name: destination_station_complex_id, dtype: int64

Destination complex id: 122
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
122 is not in stops_after

Destination complex id: 398
Connecting lines: []
From 120 to 398, shortest paths: [['120', '602', '398']]
Total paths: 1, num paths: 1
37
df_tmp:  43    398
Name: destination_station_complex_id, dtype: int64

Destination complex id: 399
Connecting lines: []
From 120 to 399, shortest paths: [['120', '602', '399']]
Total paths: 1, num paths: 1
38
df_tmp:  1    399
Name: destination_station_complex_id, dtype: int64

Destination complex id: 622
Connecting lines: []
From 120 to 622, shortest paths: [['120', '602', '622'], ['120', '621', '622']]
Total paths: 2, num paths: 1
39
df_tmp:  27    622
Name: destination_station_complex_id, dtype: int64

Destination complex id: 169
Connecting lines: []
From 120 to 169, shortest paths: [['120', '618', '169'], ['120', '621', '169']]
Total paths: 2, num paths: 1
40
df_tmp:  164    169
Name: destination_station_complex_id, dtype: int64

Destination complex id: 404
Connecting lines: []
From 120 to 404, shortest paths: [['120', '602', '404']]
Total paths: 1, num paths: 1
41
df_tmp:  200    404
Name: destination_station_complex_id, dtype: int64

Destination complex id: 407
Connecting lines: []
From 120 to 407, shortest paths: [['120', '602', '407']]
Total paths: 1, num paths: 1
42
df_tmp:  108    407
Name: destination_station_complex_id, dtype: int64

Destination complex id: 477
Connecting lines: []
From 120 to 477, shortest paths: [['120', '602', '477']]
Total paths: 1, num paths: 1
43
df_tmp:  104    477
Name: destination_station_complex_id, dtype: int64

Destination complex id: 123
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
123 is not in stops_after

Destination complex id: 165
Connecting lines: []
From 120 to 165, shortest paths: [['120', '618', '165'], ['120', '621', '165']]
Total paths: 2, num paths: 1
45
df_tmp:  149    165
Name: destination_station_complex_id, dtype: int64

Destination complex id: 624
Connecting lines: []
From 120 to 624, shortest paths: [['120', '602', '624'], ['120', '601', '624'], ['120', '618', '624'], ['120', '621', '624']]
Total paths: 4, num paths: 3
46
df_tmp:  117    624
Name: destination_station_complex_id, dtype: int64

Destination complex id: 8
Connecting lines: []
From 120 to 8, shortest paths: [['120', '602', '8']]
Total paths: 1, num paths: 1
47
df_tmp:  215    8
Name: destination_station_complex_id, dtype: int64

Destination complex id: 629
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
629 is not in stops_after

Destination complex id: 224
Connecting lines: []
From 120 to 224, shortest paths: [['120', '601', '224']]
Total paths: 1, num paths: 1
49
df_tmp:  144    224
Name: destination_station_complex_id, dtype: int64

Destination complex id: 625
Connecting lines: []
From 120 to 625, shortest paths: [['120', '601', '625'], ['120', '621', '625']]
Total paths: 2, num paths: 1
50
df_tmp:  95    625
Name: destination_station_complex_id, dtype: int64

Destination complex id: 276
Connecting lines: []
From 120 to 276, shortest paths: [['120', '618', '276']]
Total paths: 1, num paths: 1
51
df_tmp:  154    276
Name: destination_station_complex_id, dtype: int64

Destination complex id: 413
Connecting lines: []
From 120 to 413, shortest paths: [['120', '602', '413']]
Total paths: 1, num paths: 1
52
df_tmp:  223    413
Name: destination_station_complex_id, dtype: int64

Destination complex id: 323
Connecting lines: []
From 120 to 323, shortest paths: [['120', '601', '323']]
Total paths: 1, num paths: 1
53
df_tmp:  46    323
Name: destination_station_complex_id, dtype: int64

Destination complex id: 307
Connecting lines: []
From 120 to 307, shortest paths: [['120', '601', '307']]
Total paths: 1, num paths: 1
54
df_tmp:  188    307
Name: destination_station_complex_id, dtype: int64

Destination complex id: 313
Connecting lines: []
From 120 to 313, shortest paths: [['120', '601', '313']]
Total paths: 1, num paths: 1
55
df_tmp:  236    313
Name: destination_station_complex_id, dtype: int64

Destination complex id: 318
Connecting lines: []
From 120 to 318, shortest paths: [['120', '601', '318']]
Total paths: 1, num paths: 1
56
df_tmp:  34    318
Name: destination_station_complex_id, dtype: int64

Destination complex id: 471
Connecting lines: []
From 120 to 471, shortest paths: [['120', '602', '610', '471'], ['120', '602', '611', '471'], ['120', '601', '611', '471'], ['120', '618', '611', '471'], ['120', '621', '611', '471'], ['120', '602', '461', '471'], ['120', '601', '609', '471'], ['120', '601', '616', '471'], ['120', '618', '616', '471'], ['120', '618', '606', '471'], ['120', '629', '606', '471']]
Total paths: 11, num paths: 9
57
df_tmp:  240    471
Name: destination_station_complex_id, dtype: int64

Destination complex id: 327
Connecting lines: []
From 120 to 327, shortest paths: [['120', '601', '327']]
Total paths: 1, num paths: 1
58
df_tmp:  23    327
Name: destination_station_complex_id, dtype: int64

Destination complex id: 129
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
129 is not in stops_after

Destination complex id: 326
Connecting lines: []
From 120 to 326, shortest paths: [['120', '601', '326']]
Total paths: 1, num paths: 1
60
df_tmp:  91    326
Name: destination_station_complex_id, dtype: int64

Destination complex id: 314
Connecting lines: []
From 120 to 314, shortest paths: [['120', '601', '314']]
Total paths: 1, num paths: 1
61
df_tmp:  52    314
Name: destination_station_complex_id, dtype: int64

Destination complex id: 635
Connecting lines: []
From 120 to 635, shortest paths: [['120', '602', '635'], ['120', '601', '635']]
Total paths: 2, num paths: 2
62
df_tmp:  28    635
Name: destination_station_complex_id, dtype: int64

Destination complex id: 414
Connecting lines: []
From 120 to 414, shortest paths: [['120', '602', '414']]
Total paths: 1, num paths: 1
63
df_tmp:  160    414
Name: destination_station_complex_id, dtype: int64

Destination complex id: 130
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
130 is not in stops_after

Destination complex id: 101
Connecting lines: []
From 120 to 101, shortest paths: [['120', '621', '101']]
Total paths: 1, num paths: 0
65

Destination complex id: 310
Connecting lines: []
From 120 to 310, shortest paths: [['120', '601', '310']]
Total paths: 1, num paths: 1
66
df_tmp:  9    310
Name: destination_station_complex_id, dtype: int64

Destination complex id: 283
Connecting lines: []
From 120 to 283, shortest paths: [['120', '629', '283']]
Total paths: 1, num paths: 0
67

Destination complex id: 232
Connecting lines: []
From 120 to 232, shortest paths: [['120', '601', '232']]
Total paths: 1, num paths: 1
68
df_tmp:  48    232
Name: destination_station_complex_id, dtype: int64

Destination complex id: 312
Connecting lines: []
From 120 to 312, shortest paths: [['120', '601', '312']]
Total paths: 1, num paths: 1
69
df_tmp:  77    312
Name: destination_station_complex_id, dtype: int64

Destination complex id: 113
Connecting lines: []
From 120 to 113, shortest paths: [['120', '630', '113']]
Total paths: 1, num paths: 0
70

Destination complex id: 114
Connecting lines: []
From 120 to 114, shortest paths: [['120', '630', '114']]
Total paths: 1, num paths: 0
71

Destination complex id: 476
Connecting lines: []
From 120 to 476, shortest paths: [['120', '602', '476']]
Total paths: 1, num paths: 1
72
df_tmp:  0    476
Name: destination_station_complex_id, dtype: int64

Destination complex id: 162
Connecting lines: []
From 120 to 162, shortest paths: [['120', '618', '162'], ['120', '621', '162']]
Total paths: 2, num paths: 1
73
df_tmp:  261    162
Name: destination_station_complex_id, dtype: int64

Destination complex id: 325
Connecting lines: []
From 120 to 325, shortest paths: [['120', '601', '325']]
Total paths: 1, num paths: 1
74
df_tmp:  66    325
Name: destination_station_complex_id, dtype: int64

Destination complex id: 159
Connecting lines: []
From 120 to 159, shortest paths: [['120', '618', '159'], ['120', '621', '159']]
Total paths: 2, num paths: 1
75
df_tmp:  150    159
Name: destination_station_complex_id, dtype: int64

Destination complex id: 97
Connecting lines: []
From 120 to 97, shortest paths: [['120', '630', '97'], ['120', '621', '97']]
Total paths: 2, num paths: 0
76

Destination complex id: 396
Connecting lines: []
From 120 to 396, shortest paths: [['120', '602', '396']]
Total paths: 1, num paths: 1
77
df_tmp:  230    396
Name: destination_station_complex_id, dtype: int64

Destination complex id: 160
Connecting lines: []
From 120 to 160, shortest paths: [['120', '618', '160'], ['120', '621', '160']]
Total paths: 2, num paths: 1
78
df_tmp:  170    160
Name: destination_station_complex_id, dtype: int64

Destination complex id: 320
Connecting lines: []
From 120 to 320, shortest paths: [['120', '601', '320']]
Total paths: 1, num paths: 1
79
df_tmp:  65    320
Name: destination_station_complex_id, dtype: int64

Destination complex id: 289
Connecting lines: []
From 120 to 289, shortest paths: [['120', '629', '289']]
Total paths: 1, num paths: 0
80

Destination complex id: 99
Connecting lines: []
From 120 to 99, shortest paths: [['120', '621', '99']]
Total paths: 1, num paths: 0
81

Destination complex id: 605
Connecting lines: []
From 120 to 605, shortest paths: [['120', '601', '605'], ['120', '618', '605'], ['120', '621', '605']]
Total paths: 3, num paths: 2
82
df_tmp:  151    605
Name: destination_station_complex_id, dtype: int64

Destination complex id: 277
Connecting lines: []
From 120 to 277, shortest paths: [['120', '618', '277']]
Total paths: 1, num paths: 1
83
df_tmp:  235    277
Name: destination_station_complex_id, dtype: int64

Destination complex id: 328
Connecting lines: []
From 120 to 328, shortest paths: [['120', '601', '328']]
Total paths: 1, num paths: 1
84
df_tmp:  20    328
Name: destination_station_complex_id, dtype: int64

Destination complex id: 58
Connecting lines: []
From 120 to 58, shortest paths: [['120', '602', '58'], ['120', '601', '58']]
Total paths: 2, num paths: 2
85
df_tmp:  205    58
Name: destination_station_complex_id, dtype: int64

Destination complex id: 447
Connecting lines: []
From 120 to 447, shortest paths: [['120', '602', '610', '447'], ['120', '602', '611', '447'], ['120', '601', '611', '447'], ['120', '618', '611', '447'], ['120', '621', '611', '447'], ['120', '602', '461', '447'], ['120', '601', '609', '447'], ['120', '601', '616', '447'], ['120', '618', '616', '447'], ['120', '618', '606', '447'], ['120', '629', '606', '447']]
Total paths: 11, num paths: 9
86
df_tmp:  239    447
Name: destination_station_complex_id, dtype: int64

Destination complex id: 291
Connecting lines: []
From 120 to 291, shortest paths: [['120', '629', '291']]
Total paths: 1, num paths: 0
87

Destination complex id: 288
Connecting lines: []
From 120 to 288, shortest paths: [['120', '629', '288']]
Total paths: 1, num paths: 0
88

Destination complex id: 26
Connecting lines: []
From 120 to 26, shortest paths: [['120', '602', '26']]
Total paths: 1, num paths: 1
89
df_tmp:  3    26
Name: destination_station_complex_id, dtype: int64

Destination complex id: 617
Connecting lines: []
From 120 to 617, shortest paths: [['120', '602', '617'], ['120', '601', '617']]
Total paths: 2, num paths: 2
90
df_tmp:  67    617
Name: destination_station_complex_id, dtype: int64

Destination complex id: 321
Connecting lines: []
From 120 to 321, shortest paths: [['120', '601', '321']]
Total paths: 1, num paths: 1
91
df_tmp:  81    321
Name: destination_station_complex_id, dtype: int64

Destination complex id: 31
Connecting lines: []
From 120 to 31, shortest paths: [['120', '602', '31']]
Total paths: 1, num paths: 1
92
df_tmp:  37    31
Name: destination_station_complex_id, dtype: int64

Destination complex id: 234
Connecting lines: []
From 120 to 234, shortest paths: [['120', '601', '234']]
Total paths: 1, num paths: 1
93
df_tmp:  30    234
Name: destination_station_complex_id, dtype: int64

Destination complex id: 284
Connecting lines: []
From 120 to 284, shortest paths: [['120', '629', '284']]
Total paths: 1, num paths: 0
94

Destination complex id: 448
Connecting lines: []
From 120 to 448, shortest paths: [['120', '602', '610', '448'], ['120', '602', '611', '448'], ['120', '601', '611', '448'], ['120', '618', '611', '448'], ['120', '621', '611', '448'], ['120', '602', '461', '448'], ['120', '601', '609', '448'], ['120', '601', '616', '448'], ['120', '618', '616', '448'], ['120', '618', '606', '448'], ['120', '629', '606', '448']]
Total paths: 11, num paths: 9
95
df_tmp:  96    448
Name: destination_station_complex_id, dtype: int64

Destination complex id: 103
Connecting lines: []
From 120 to 103, shortest paths: [['120', '621', '103']]
Total paths: 1, num paths: 0
96

Destination complex id: 292

/var/folders/vv/8v01rf7n71748vxd0m5kt_dr0000gn/T/ipykernel_97437/4148522952.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)

df_tmp:  173    445
Name: destination_station_complex_id, dtype: int64

Destination complex id: 303
Connecting lines: []
From 120 to 303, shortest paths: [['120', '601', '303']]
Total paths: 1, num paths: 1
142
df_tmp:  32    303
Name: destination_station_complex_id, dtype: int64

Destination complex id: 278
Connecting lines: []
From 120 to 278, shortest paths: [['120', '618', '278'], ['120', '621', '278']]
Total paths: 2, num paths: 1
143
df_tmp:  102    278
Name: destination_station_complex_id, dtype: int64

Destination complex id: 109
Connecting lines: []
From 120 to 109, shortest paths: [['120', '630', '109']]
Total paths: 1, num paths: 0
144

Destination complex id: 392
Connecting lines: []
From 120 to 392, shortest paths: [['120', '602', '392']]
Total paths: 1, num paths: 1
145
df_tmp:  18    392
Name: destination_station_complex_id, dtype: int64

Destination complex id: 175
Connecting lines: []
From 120 to 175, shortest paths: [['120', '618', '175'], ['120', '629', '175'], ['120', '621', '175']]
Total paths: 3, num paths: 1
146
df_tmp:  8    175
Name: destination_station_complex_id, dtype: int64

Destination complex id: 182
Connecting lines: []
From 120 to 182, shortest paths: [['120', '618', '182'], ['120', '621', '182']]
Total paths: 2, num paths: 1
147
df_tmp:  225    182
Name: destination_station_complex_id, dtype: int64

Destination complex id: 620
Connecting lines: []
From 120 to 620, shortest paths: [['120', '602', '620'], ['120', '601', '620']]
Total paths: 2, num paths: 2
148
df_tmp:  181    620
Name: destination_station_complex_id, dtype: int64

Destination complex id: 606
Connecting lines: []
From 120 to 606, shortest paths: [['120', '618', '606'], ['120', '629', '606']]
Total paths: 2, num paths: 1
149
df_tmp:  220    606
Name: destination_station_complex_id, dtype: int64

Destination complex id: 464
Connecting lines: []
From 120 to 464, shortest paths: [['120', '602', '610', '464'], ['120', '602', '611', '464'], ['120', '601', '611', '464'], ['120', '618', '611', '464'], ['120', '621', '611', '464'], ['120', '602', '461', '464'], ['120', '601', '609', '464'], ['120', '601', '616', '464'], ['120', '618', '616', '464'], ['120', '618', '606', '464'], ['120', '629', '606', '464']]
Total paths: 11, num paths: 9
150
df_tmp:  16    464
Name: destination_station_complex_id, dtype: int64

Destination complex id: 20
Connecting lines: []
From 120 to 20, shortest paths: [['120', '602', '20']]
Total paths: 1, num paths: 1
151
df_tmp:  115    20
Name: destination_station_complex_id, dtype: int64

Destination complex id: 203
Connecting lines: []
From 120 to 203, shortest paths: []
Total paths: 0, num paths: 0
152

Destination complex id: 202
Connecting lines: []
From 120 to 202, shortest paths: []
Total paths: 0, num paths: 0
153

Destination complex id: 143
Connecting lines: []
From 120 to 143, shortest paths: [['120', '618', '143'], ['120', '621', '143']]
Total paths: 2, num paths: 1
154
df_tmp:  101    143
Name: destination_station_complex_id, dtype: int64

Destination complex id: 93
Connecting lines: []
From 120 to 93, shortest paths: [['120', '621', '93']]
Total paths: 1, num paths: 0
155

Destination complex id: 287
Connecting lines: []
From 120 to 287, shortest paths: [['120', '629', '287']]
Total paths: 1, num paths: 0
156

Destination complex id: 449
Connecting lines: []
From 120 to 449, shortest paths: [['120', '602', '610', '449'], ['120', '602', '611', '449'], ['120', '601', '611', '449'], ['120', '618', '611', '449'], ['120', '621', '611', '449'], ['120', '602', '461', '449'], ['120', '601', '609', '449'], ['120', '601', '616', '449'], ['120', '618', '616', '449'], ['120', '618', '606', '449'], ['120', '629', '606', '449']]
Total paths: 11, num paths: 9
157
df_tmp:  153    449
Name: destination_station_complex_id, dtype: int64

Destination complex id: 349
Connecting lines: []
From 120 to 349, shortest paths: [['120', '602', '349']]
Total paths: 1, num paths: 1
158
df_tmp:  120    349
Name: destination_station_complex_id, dtype: int64

Destination complex id: 151
Connecting lines: []
From 120 to 151, shortest paths: [['120', '618', '151'], ['120', '621', '151']]
Total paths: 2, num paths: 1
159
df_tmp:  68    151
Name: destination_station_complex_id, dtype: int64

Destination complex id: 298
Connecting lines: []
From 120 to 298, shortest paths: [['120', '601', '298']]
Total paths: 1, num paths: 1
160
df_tmp:  119    298
Name: destination_station_complex_id, dtype: int64

Destination complex id: 37
Connecting lines: []
From 120 to 37, shortest paths: [['120', '602', '620', '37'], ['120', '601', '620', '37'], ['120', '602', '617', '37'], ['120', '601', '617', '37'], ['120', '602', '635', '37'], ['120', '601', '635', '37'], ['120', '602', '636', '37'], ['120', '601', '636', '37'], ['120', '618', '636', '37'], ['120', '621', '636', '37'], ['120', '602', '26', '37'], ['120', '602', '28', '37'], ['120', '602', '608', '37'], ['120', '601', '608', '37'], ['120', '629', '608', '37'], ['120', '602', '30', '37'], ['120', '602', '31', '37'], ['120', '602', '32', '37'], ['120', '602', '33', '37'], ['120', '602', '34', '37'], ['120', '602', '35', '37']]
Total paths: 21, num paths: 19
161
df_tmp:  182    37
Name: destination_station_complex_id, dtype: int64

Destination complex id: 383
Connecting lines: []
From 120 to 383, shortest paths: [['120', '602', '383']]
Total paths: 1, num paths: 1
162
df_tmp:  127    383
Name: destination_station_complex_id, dtype: int64

Destination complex id: 305
Connecting lines: []
From 120 to 305, shortest paths: [['120', '601', '305']]
Total paths: 1, num paths: 1
163
df_tmp:  158    305
Name: destination_station_complex_id, dtype: int64

Destination complex id: 57
Connecting lines: []
From 120 to 57, shortest paths: [['120', '602', '57'], ['120', '601', '57']]
Total paths: 2, num paths: 2
164
df_tmp:  162    57
Name: destination_station_complex_id, dtype: int64

Destination complex id: 427
Connecting lines: []
From 120 to 427, shortest paths: [['120', '601', '427']]
Total paths: 1, num paths: 1
165
df_tmp:  58    427
Name: destination_station_complex_id, dtype: int64

Destination complex id: 144
Connecting lines: []
From 120 to 144, shortest paths: [['120', '618', '144'], ['120', '621', '144']]
Total paths: 2, num paths: 1
166
df_tmp:  254    144
Name: destination_station_complex_id, dtype: int64

Destination complex id: 388
Connecting lines: []
From 120 to 388, shortest paths: [['120', '602', '388']]
Total paths: 1, num paths: 1
167
df_tmp:  78    388
Name: destination_station_complex_id, dtype: int64

Destination complex id: 34
Connecting lines: []
From 120 to 34, shortest paths: [['120', '602', '34']]
Total paths: 1, num paths: 1
168
df_tmp:  258    34
Name: destination_station_complex_id, dtype: int64

Destination complex id: 352
Connecting lines: []
From 120 to 352, shortest paths: [['120', '602', '352']]
Total paths: 1, num paths: 1
169
df_tmp:  242    352
Name: destination_station_complex_id, dtype: int64

Destination complex id: 87
Connecting lines: []
From 120 to 87, shortest paths: [['120', '621', '87']]
Total paths: 1, num paths: 0
170

Destination complex id: 261
Connecting lines: []
From 120 to 261, shortest paths: [['120', '601', '261'], ['120', '618', '261']]
Total paths: 2, num paths: 2
171
df_tmp:  155    261
Name: destination_station_complex_id, dtype: int64

Destination complex id: 216
Connecting lines: []
From 120 to 216, shortest paths: [['120', '602', '604', '216'], ['120', '602', '619', '216'], ['120', '601', '619', '216'], ['120', '602', '617', '216'], ['120', '601', '617', '216'], ['120', '602', '607', '216'], ['120', '601', '607', '216'], ['120', '602', '26', '216'], ['120', '602', '28', '216'], ['120', '602', '608', '216'], ['120', '601', '608', '216'], ['120', '629', '608', '216'], ['120', '602', '30', '216'], ['120', '602', '31', '216'], ['120', '602', '32', '216'], ['120', '602', '615', '216'], ['120', '602', '58', '216'], ['120', '601', '58', '216'], ['120', '602', '41', '216'], ['120', '602', '42', '216'], ['120', '602', '44', '216'], ['120', '602', '47', '216'], ['120', '602', '51', '216'], ['120', '602', '54', '216'], ['120', '602', '55', '216'], ['120', '601', '614', '216'], ['120', '618', '614', '216'], ['120', '621', '614', '216'], ['120', '601', '609', '216'], ['120', '601', '225', '216'], ['120', '601', '167', '216'], ['120', '618', '167', '216'], ['120', '621', '167', '216'], ['120', '618', '160', '216'], ['120', '621', '160', '216'], ['120', '618', '159', '216'], ['120', '621', '159', '216'], ['120', '618', '158', '216'], ['120', '621', '158', '216'], ['120', '618', '157', '216'], ['120', '621', '157', '216'], ['120', '618', '156', '216'], ['120', '621', '156', '216'], ['120', '618', '155', '216'], ['120', '621', '155', '216'], ['120', '618', '154', '216'], ['120', '621', '154', '216'], ['120', '618', '153', '216'], ['120', '621', '153', '216'], ['120', '618', '152', '216'], ['120', '621', '152', '216'], ['120', '618', '151', '216'], ['120', '621', '151', '216'], ['120', '618', '277', '216']]
Total paths: 54, num paths: 41
172
df_tmp:  51    216
Name: destination_station_complex_id, dtype: int64

Destination complex id: 316
Connecting lines: []
From 120 to 316, shortest paths: [['120', '601', '316']]
Total paths: 1, num paths: 1
173
df_tmp:  111    316
Name: destination_station_complex_id, dtype: int64

Destination complex id: 304
Connecting lines: []
From 120 to 304, shortest paths: [['120', '601', '304']]
Total paths: 1, num paths: 1
174
df_tmp:  4    304
Name: destination_station_complex_id, dtype: int64

Destination complex id: 107
Connecting lines: []
From 120 to 107, shortest paths: [['120', '621', '107']]
Total paths: 1, num paths: 0
175

Destination complex id: 459
Connecting lines: []
From 120 to 459, shortest paths: [['120', '602', '610', '459'], ['120', '602', '611', '459'], ['120', '601', '611', '459'], ['120', '618', '611', '459'], ['120', '621', '611', '459'], ['120', '602', '461', '459'], ['120', '601', '609', '459'], ['120', '601', '616', '459'], ['120', '618', '616', '459'], ['120', '618', '606', '459'], ['120', '629', '606', '459']]
Total paths: 11, num paths: 9
176
df_tmp:  264    459
Name: destination_station_complex_id, dtype: int64

Destination complex id: 188
Connecting lines: []
From 120 to 188, shortest paths: [['120', '618', '188'], ['120', '621', '188']]
Total paths: 2, num paths: 1
177
df_tmp:  260    188
Name: destination_station_complex_id, dtype: int64

Destination complex id: 47
Connecting lines: []
From 120 to 47, shortest paths: [['120', '602', '47']]
Total paths: 1, num paths: 1
178
df_tmp:  5    47
Name: destination_station_complex_id, dtype: int64

Destination complex id: 424
Connecting lines: []
From 120 to 424, shortest paths: [['120', '601', '424']]
Total paths: 1, num paths: 1
179
df_tmp:  21    424
Name: destination_station_complex_id, dtype: int64

Destination complex id: 237
Connecting lines: []
From 120 to 237, shortest paths: [['120', '601', '237'], ['120', '629', '237']]
Total paths: 2, num paths: 1
180
df_tmp:  146    237
Name: destination_station_complex_id, dtype: int64

Destination complex id: 133
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
133 is not in stops_after

Destination complex id: 108
Connecting lines: []
From 120 to 108, shortest paths: [['120', '630', '108']]
Total paths: 1, num paths: 0
182

Destination complex id: 89
Connecting lines: []
From 120 to 89, shortest paths: [['120', '621', '89']]
Total paths: 1, num paths: 0
183

Destination complex id: 55
Connecting lines: []
From 120 to 55, shortest paths: [['120', '602', '55']]
Total paths: 1, num paths: 1
184
df_tmp:  232    55
Name: destination_station_complex_id, dtype: int64

Destination complex id: 200
Connecting lines: []
From 120 to 200, shortest paths: []
Total paths: 0, num paths: 0
185

Destination complex id: 214
Connecting lines: []
From 120 to 214, shortest paths: [['120', '602', '604', '214'], ['120', '602', '619', '214'], ['120', '601', '619', '214'], ['120', '602', '617', '214'], ['120', '601', '617', '214'], ['120', '602', '607', '214'], ['120', '601', '607', '214'], ['120', '602', '26', '214'], ['120', '602', '28', '214'], ['120', '602', '608', '214'], ['120', '601', '608', '214'], ['120', '629', '608', '214'], ['120', '602', '30', '214'], ['120', '602', '31', '214'], ['120', '602', '32', '214'], ['120', '602', '615', '214'], ['120', '602', '58', '214'], ['120', '601', '58', '214'], ['120', '602', '41', '214'], ['120', '602', '42', '214'], ['120', '602', '44', '214'], ['120', '602', '47', '214'], ['120', '602', '51', '214'], ['120', '602', '54', '214'], ['120', '602', '55', '214'], ['120', '601', '614', '214'], ['120', '618', '614', '214'], ['120', '621', '614', '214'], ['120', '601', '609', '214'], ['120', '601', '225', '214'], ['120', '601', '167', '214'], ['120', '618', '167', '214'], ['120', '621', '167', '214'], ['120', '618', '160', '214'], ['120', '621', '160', '214'], ['120', '618', '159', '214'], ['120', '621', '159', '214'], ['120', '618', '158', '214'], ['120', '621', '158', '214'], ['120', '618', '157', '214'], ['120', '621', '157', '214'], ['120', '618', '156', '214'], ['120', '621', '156', '214'], ['120', '618', '155', '214'], ['120', '621', '155', '214'], ['120', '618', '154', '214'], ['120', '621', '154', '214'], ['120', '618', '153', '214'], ['120', '621', '153', '214'], ['120', '618', '152', '214'], ['120', '621', '152', '214'], ['120', '618', '151', '214'], ['120', '621', '151', '214'], ['120', '618', '277', '214']]
Total paths: 54, num paths: 41
186
df_tmp:  253    214
Name: destination_station_complex_id, dtype: int64

Destination complex id: 141
Connecting lines: []
From 120 to 141, shortest paths: [['120', '602', '626', '141'], ['120', '601', '626', '141'], ['120', '602', '42', '141'], ['120', '618', '627', '141'], ['120', '621', '627', '141']]
Total paths: 5, num paths: 4
187
df_tmp:  40    141
Name: destination_station_complex_id, dtype: int64

Destination complex id: 205
Connecting lines: []
From 120 to 205, shortest paths: []
Total paths: 0, num paths: 0
188

Destination complex id: 86
Connecting lines: []
From 120 to 86, shortest paths: [['120', '621', '86']]
Total paths: 1, num paths: 0
189

Destination complex id: 201
Connecting lines: []
From 120 to 201, shortest paths: []
Total paths: 0, num paths: 0
190

Destination complex id: 458
Connecting lines: []
From 120 to 458, shortest paths: [['120', '602', '610', '458'], ['120', '602', '611', '458'], ['120', '601', '611', '458'], ['120', '618', '611', '458'], ['120', '621', '611', '458'], ['120', '602', '461', '458'], ['120', '601', '609', '458'], ['120', '601', '616', '458'], ['120', '618', '616', '458'], ['120', '618', '606', '458'], ['120', '629', '606', '458']]
Total paths: 11, num paths: 9
191
df_tmp:  195    458
Name: destination_station_complex_id, dtype: int64

Destination complex id: 240
Connecting lines: []
From 120 to 240, shortest paths: [['120', '601', '240'], ['120', '629', '240']]
Total paths: 2, num paths: 1
192
df_tmp:  62    240
Name: destination_station_complex_id, dtype: int64

Destination complex id: 71
Connecting lines: []
From 120 to 71, shortest paths: [['120', '602', '71']]
Total paths: 1, num paths: 1
193
df_tmp:  231    71
Name: destination_station_complex_id, dtype: int64

Destination complex id: 4
Connecting lines: []
From 120 to 4, shortest paths: [['120', '602', '4']]
Total paths: 1, num paths: 1
194
df_tmp:  54    4
Name: destination_station_complex_id, dtype: int64

Destination complex id: 44
Connecting lines: []
From 120 to 44, shortest paths: [['120', '602', '44']]
Total paths: 1, num paths: 1
195
df_tmp:  193    44
Name: destination_station_complex_id, dtype: int64

Destination complex id: 254
Connecting lines: []
From 120 to 254, shortest paths: [['120', '601', '254']]
Total paths: 1, num paths: 1
196
df_tmp:  234    254
Name: destination_station_complex_id, dtype: int64

Destination complex id: 451
Connecting lines: []
From 120 to 451, shortest paths: [['120', '602', '610', '451'], ['120', '602', '611', '451'], ['120', '601', '611', '451'], ['120', '618', '611', '451'], ['120', '621', '611', '451'], ['120', '602', '461', '451'], ['120', '601', '609', '451'], ['120', '601', '616', '451'], ['120', '618', '616', '451'], ['120', '618', '606', '451'], ['120', '629', '606', '451']]
Total paths: 11, num paths: 9
197
df_tmp:  218    451
Name: destination_station_complex_id, dtype: int64

Destination complex id: 271
Connecting lines: []
From 120 to 271, shortest paths: [['120', '601', '271'], ['120', '618', '271']]
Total paths: 2, num paths: 2
198
df_tmp:  262    271
Name: destination_station_complex_id, dtype: int64

Destination complex id: 53
Connecting lines: []
From 120 to 53, shortest paths: [['120', '602', '53']]
Total paths: 1, num paths: 1
199
df_tmp:  25    53
Name: destination_station_complex_id, dtype: int64

Destination complex id: 280
Connecting lines: []
From 120 to 280, shortest paths: [['120', '618', '280']]
Total paths: 1, num paths: 1
200
df_tmp:  83    280
Name: destination_station_complex_id, dtype: int64

Destination complex id: 131
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
131 is not in stops_after

Destination complex id: 136
Connecting lines: ['L']
Stops after stop 120: [119, 118, 602, 601, 618]
136 is not in stops_after

Destination complex id: 273
Connecting lines: []
From 120 to 273, shortest paths: [['120', '618', '273']]
Total paths: 1, num paths: 1
203
df_tmp:  191    273
Name: destination_station_complex_id, dtype: int64

Destination complex id: 385
Connecting lines: []
From 120 to 385, shortest paths: [['120', '602', '385']]
Total paths: 1, num paths: 1
204
df_tmp:  124    385
Name: destination_station_complex_id, dtype: int64

Destination complex id: 46
Connecting lines: []
From 120 to 46, shortest paths: [['120', '602', '46']]
Total paths: 1, num paths: 1
205
df_tmp:  99    46
Name: destination_station_complex_id, dtype: int64

Destination complex id: 368
Connecting lines: []
From 120 to 368, shortest paths: [['120', '602', '368']]
Total paths: 1, num paths: 1
206
df_tmp:  183    368
Name: destination_station_complex_id, dtype: int64

Destination complex id: 380
Connecting lines: []
From 120 to 380, shortest paths: [['120', '602', '380']]
Total paths: 1, num paths: 1
207
df_tmp:  227    380
Name: destination_station_complex_id, dtype: int64

Destination complex id: 359
Connecting lines: []
From 120 to 359, shortest paths: [['120', '601', '359']]
Total paths: 1, num paths: 1
208
df_tmp:  147    359
Name: destination_station_complex_id, dtype: int64

Destination complex id: 460
Connecting lines: []
From 120 to 460, shortest paths: [['120', '602', '610', '460'], ['120', '602', '611', '460'], ['120', '601', '611', '460'], ['120', '618', '611', '460'], ['120', '621', '611', '460'], ['120', '602', '461', '460'], ['120', '601', '609', '460'], ['120', '601', '616', '460'], ['120', '618', '616', '460'], ['120', '618', '606', '460'], ['120', '629', '606', '460']]
Total paths: 11, num paths: 9
209
df_tmp:  243    460
Name: destination_station_complex_id, dtype: int64

Destination complex id: 353
Connecting lines: []
From 120 to 353, shortest paths: [['120', '601', '353']]
Total paths: 1, num paths: 1
210
df_tmp:  224    353
Name: destination_station_complex_id, dtype: int64

Destination complex id: 190
Connecting lines: []
From 120 to 190, shortest paths: [['120', '618', '190'], ['120', '621', '190']]
Total paths: 2, num paths: 1
211
df_tmp:  184    190
Name: destination_station_complex_id, dtype: int64

Destination complex id: 3
Connecting lines: []
From 120 to 3, shortest paths: [['120', '602', '3']]
Total paths: 1, num paths: 1
212
df_tmp:  165    3
Name: destination_station_complex_id, dtype: int64

Destination complex id: 418
Connecting lines: []
From 120 to 418, shortest paths: [['120', '601', '418']]
Total paths: 1, num paths: 1
213
df_tmp:  222    418
Name: destination_station_complex_id, dtype: int64


,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,9,Monday,10,120,Bedford Av (L),602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",130.6930
1,2025,9,Monday,10,120,Bedford Av (L),618,"14 St (A,C,E)/8 Av (L)",70.8448
2,2025,9,Monday,10,120,Bedford Av (L),601,"14 St (F,M,1,2,3)/6 Av (L)",43.5630
3,2025,9,Monday,10,120,Bedford Av (L),119,1 Av (L),42.7778
4,2025,9,Monday,10,120,Bedford Av (L),610,"Grand Central-42 St (S,4,5,6,7)",41.5626
...,...,...,...,...,...,...,...,...,...
209,2025,9,Monday,10,120,Bedford Av (L),156,"103 St (C,B)",0.1112
210,2025,9,Monday,10,120,Bedford Av (L),421,"Gun Hill Rd (2,5)",0.2224
211,2025,9,Monday,10,120,Bedford Av (L),5,"36 Av (N,W)",0.2206
212,2025,9,Monday,10,120,Bedford Av (L),30,Prospect Av (R),0.2206
213,2025,9,Monday,10,120,Bedford Av (L),48,Avenue H (Q),0.2206

In [8]:
df["estimated_average_ridership"].sum() # number of people who boarded the L train at Bedford Av at 9 am on Tuesday in Febuary 2025.

np.float64(867.38757163385)

In [9]:
def get_offboards_data(complex_id, year: int = 2025, month: int = 9, day_of_week: str = "Monday", hour_of_day: str = "10"):
    from socrata_od_client import get_ridership_data

    # Get weekday ridership for May 2024 at 9am from station 623
    df = get_ridership_data(
        year=year,
        month=month,
        day_of_week=day_of_week,
        hour_of_day=hour_of_day,
        destination_station_complex_id=complex_id
    )

    df_ = df.sort_values('estimated_average_ridership', ascending=False)
    return df_

df_offboards_120 = get_offboards_data("120")
df_offboards_120

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
290,2025,9,Monday,10,119,1 Av (L),120,Bedford Av (L),61.3278
220,2025,9,Monday,10,602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",120,Bedford Av (L),42.7488
75,2025,9,Monday,10,630,"Myrtle-Wyckoff Avs (L,M)",120,Bedford Av (L),40.4088
70,2025,9,Monday,10,127,DeKalb Av (L),120,Bedford Av (L),39.3482
207,2025,9,Monday,10,611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",120,Bedford Av (L),32.3374
...,...,...,...,...,...,...,...,...,...
249,2025,9,Monday,10,241,"15 St-Prospect Park (F,G)",120,Bedford Av (L),0.2228
325,2025,9,Monday,10,334,"Clark St (2,3)",120,Bedford Av (L),0.2208
226,2025,9,Monday,10,145,190 St (A),120,Bedford Av (L),0.2202
237,2025,9,Monday,10,303,157 St (1),120,Bedford Av (L),0.2196
8,2025,9,Monday,10,294,238 St (1),120,Bedford Av (L),0.2000

In [10]:
# 0 = north/east-bound, 1 = south/west-bound
def get_offboardings(complex_id: str, line: str, direction: int, df_ : any):
    onboardings = 0
    boardings_df = pd.DataFrame(columns=df_.columns)
    stops_on_line = get_ordered_stops(line, direction, 1)

    for i in range(len(df_)):
        origin_complex_id = str(df_.iloc[i]["origin_station_complex_id"])
        connecting_lines = mta.connecting_lines(complex_id, origin_complex_id)
        
        print(f"Origin complex id: {origin_complex_id}, with name: ", mta.complex_id_to_name(origin_complex_id))
        print(f"Connecting lines: {connecting_lines}")

        if len(connecting_lines) > 0:
            if line in connecting_lines:
                stops_before = get_ordered_stops(line, 1 - direction, 1)
                stops_before = stops_before[stops_before.index(int(complex_id)) + 1:]

                print(f"Stops before stop {complex_id}: {stops_before}")

                if int(origin_complex_id) in stops_before:
                    print(f"{origin_complex_id} is in {stops_before}")
                    onboardings += df_.iloc[i]["estimated_average_ridership"] / len(connecting_lines)
                    df_tmp = df_.iloc[[i]].copy()
                    df_tmp["estimated_average_ridership"] /= len(connecting_lines)
                    boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)
                else:
                    print(f"{origin_complex_id} is not in stops_before")

        else:
            shortest_paths = mta.all_shortest_paths(complex_id, origin_complex_id)
            print(f"From {origin_complex_id} to {complex_id}, shortest paths: {shortest_paths}")

            total_paths = 0
            num_paths = 0
            distances = {}
            for path in shortest_paths:
                connections = mta.connecting_lines(path[0], path[1])

                # total_distance = 0
                # all_connections = []
                # for j in range(len(path) - 1):
                #     connecting_line = mta.connecting_lines(path[j], path[j+1])[0]
                #     stops = get_ordered_stops(connecting_line, direction, 1)
                #     path_distance = abs(stops.index(int(path[j])) - stops.index(int(path[j+1])))
                #     all_connections += connecting_line
                #     total_distance += path_distance
                # distances[str(path)] = total_distance
                # print("Path: ", path, ", Total distance: ", total_distance, ", Connections: ", all_connections)

                # distance = abs(stops_on_line.index(int(path[0])) - stops_on_line.index(int(path[1])))
                # print(f"From {path[0]} to {path[1]}, connections: {connections}, distance: {distance}")
                total_paths += len(connections)
                if line in connections:
                    if int(path[1]) in stops_before:
                        num_paths += 1
            print(f"Total paths: {total_paths}, num paths: {num_paths}")
            print(i)
            if total_paths > 0 and num_paths > 0:
                onboardings += df_.iloc[i]["estimated_average_ridership"] * (num_paths / total_paths)
                df_tmp = df_.iloc[[i]].copy()
                df_tmp["estimated_average_ridership"] *= (num_paths / total_paths)
                print("df_tmp: ", df_tmp["destination_station_complex_id"])
                boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)

    return onboardings, boardings_df

In [11]:
stops_on_line = get_ordered_stops("L", 1, 1)
print(stops_on_line)
shortest_paths = mta.all_shortest_paths("120", "611")
shortest_paths

[618, 601, 602, 118, 119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

[['120', '602', '611'],
 ['120', '601', '611'],
 ['120', '618', '611'],
 ['120', '621', '611']]

In [12]:
for path in shortest_paths:
    connections = mta.connecting_lines(path[0], path[1])
    print(connections)
    distance = abs(stops_on_line.index(int(path[0])) - stops_on_line.index(int(path[1])))
    print(distance)

['L']
3
['L']
4
['L']
5
['L']
12

In [13]:
df_offboards_120[0:5]

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
290,2025,9,Monday,10,119,1 Av (L),120,Bedford Av (L),61.3278
220,2025,9,Monday,10,602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",120,Bedford Av (L),42.7488
75,2025,9,Monday,10,630,"Myrtle-Wyckoff Avs (L,M)",120,Bedford Av (L),40.4088
70,2025,9,Monday,10,127,DeKalb Av (L),120,Bedford Av (L),39.3482
207,2025,9,Monday,10,611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",120,Bedford Av (L),32.3374

In [14]:
# 0 = north/east-bound (towards 8 Av), 1 = south/west-bound (towards Rockaway)
obs, df = get_offboardings ("120", "L", 1, df_offboards_120)

print("Offboardings: ", obs)
df

Origin complex id: 119, with name:  1 Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
119 is in [119, 118, 602, 601, 618]
Origin complex id: 602, with name:  14 St-Union Sq
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
602 is in [119, 118, 602, 601, 618]
Origin complex id: 630, with name:  Myrtle-Wyckoff Avs
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
630 is not in stops_before
Origin complex id: 127, with name:  DeKalb Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
127 is not in stops_before
Origin complex id: 611, with name:  Times Sq-42 St
Connecting lines: []
From 611 to 120, shortest paths: [['120', '602', '611'], ['120', '601', '611'], ['120', '618', '611'], ['120', '621', '611']]
Total paths: 4, num paths: 3
4
df_tmp:  207    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 601, with name:  14 St
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
601 is in [119, 118, 602, 601, 618]
Origin complex id: 164, with name:  34 St-Penn Station
Connecting lines: []
From 164 to 120, shortest paths: [['120', '618', '164'], ['120', '621', '164']]
Total paths: 2, num paths: 1
6
df_tmp:  209    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 610, with name:  Grand Central-42 St
Connecting lines: []
From 610 to 120, shortest paths: [['120', '602', '610']]
Total paths: 1, num paths: 1
7
df_tmp:  82    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 618, with name:  14 St
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
618 is in [119, 118, 602, 601, 618]
Origin complex id: 125, with name:  Morgan Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
125 is not in stops_before
Origin complex id: 124, with name:  Montrose Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
124 is not in stops_before
Origin complex id: 129, with name:  Halsey St
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
129 is not in stops_before
Origin complex id: 118, with name:  3 Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
118 is in [119, 118, 602, 601, 618]
Origin complex id: 126, with name:  Jefferson St
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
126 is not in stops_before
Origin complex id: 614, with name:  59 St-Columbus Circle
Connecting lines: []
From 614 to 120, shortest paths: [['120', '601', '614'], ['120', '618', '614'], ['120', '621', '614']]
Total paths: 3, num paths: 2
14
df_tmp:  136    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 607, with name:  34 St-Herald Sq
Connecting lines: []
From 607 to 120, shortest paths: [['120', '602', '607'], ['120', '601', '607']]
Total paths: 2, num paths: 2
15
df_tmp:  79    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 122, with name:  Graham Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
122 is not in stops_before
Origin complex id: 130, with name:  Wilson Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
130 is not in stops_before
Origin complex id: 289, with name:  Bedford-Nostrand Avs
Connecting lines: []
From 289 to 120, shortest paths: [['120', '629', '289']]
Total paths: 1, num paths: 0
18
Origin complex id: 138, with name:  Canarsie-Rockaway Pkwy
Connecting lines: ['L']

/var/folders/vv/8v01rf7n71748vxd0m5kt_dr0000gn/T/ipykernel_97437/1818246956.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)

Stops before stop 120: [119, 118, 602, 601, 618]
138 is not in stops_before
Origin complex id: 397, with name:  86 St
Connecting lines: []
From 397 to 120, shortest paths: [['120', '602', '397']]
Total paths: 1, num paths: 1
20
df_tmp:  95    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 628, with name:  Fulton St
Connecting lines: []
From 628 to 120, shortest paths: [['120', '602', '628'], ['120', '601', '628'], ['120', '618', '628'], ['120', '621', '628']]
Total paths: 4, num paths: 3
21
df_tmp:  32    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 131, with name:  Bushwick Av-Aberdeen St
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
131 is not in stops_before
Origin complex id: 612, with name:  51 St
Connecting lines: []
From 612 to 120, shortest paths: [['120', '602', '612'], ['120', '618', '612']]
Total paths: 2, num paths: 2
23
df_tmp:  256    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 619, with name:  Bleecker St
Connecting lines: []
From 619 to 120, shortest paths: [['120', '602', '619'], ['120', '601', '619']]
Total paths: 2, num paths: 2
24
df_tmp:  169    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 476, with name:  86 St
Connecting lines: []
From 476 to 120, shortest paths: [['120', '602', '476']]
Total paths: 1, num paths: 1
25
df_tmp:  36    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 97, with name:  Myrtle Av
Connecting lines: []
From 97 to 120, shortest paths: [['120', '630', '97'], ['120', '621', '97']]
Total paths: 2, num paths: 0
26
Origin complex id: 403, with name:  33 St
Connecting lines: []
From 403 to 120, shortest paths: [['120', '602', '403']]
Total paths: 1, num paths: 1
27
df_tmp:  239    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 606, with name:  Court Sq
Connecting lines: []
From 606 to 120, shortest paths: [['120', '618', '606'], ['120', '629', '606']]
Total paths: 2, num paths: 1
28
df_tmp:  113    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 456, with name:  61 St-Woodside
Connecting lines: []
From 456 to 120, shortest paths: [['120', '602', '610', '456'], ['120', '602', '611', '456'], ['120', '601', '611', '456'], ['120', '618', '611', '456'], ['120', '621', '611', '456'], ['120', '602', '461', '456'], ['120', '601', '609', '456'], ['120', '601', '616', '456'], ['120', '618', '616', '456'], ['120', '618', '606', '456'], ['120', '629', '606', '456']]
Total paths: 11, num paths: 9
29
df_tmp:  124    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 123, with name:  Grand St
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
123 is not in stops_before
Origin complex id: 313, with name:  72 St
Connecting lines: []
From 313 to 120, shortest paths: [['120', '601', '313']]
Total paths: 1, num paths: 1
31
df_tmp:  166    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 292, with name:  Fulton St
Connecting lines: []
From 292 to 120, shortest paths: [['120', '629', '292']]
Total paths: 1, num paths: 0
32
Origin complex id: 609, with name:  5 Av
Connecting lines: []
From 609 to 120, shortest paths: [['120', '601', '609']]
Total paths: 1, num paths: 1
33
df_tmp:  126    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 175, with name:  Hoyt-Schermerhorn Sts
Connecting lines: []
From 175 to 120, shortest paths: [['120', '618', '175'], ['120', '629', '175'], ['120', '621', '175']]
Total paths: 3, num paths: 1
34
df_tmp:  299    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 477, with name:  72 St
Connecting lines: []
From 477 to 120, shortest paths: [['120', '602', '477']]
Total paths: 1, num paths: 1
35
df_tmp:  89    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 162, with name:  50 St
Connecting lines: []
From 162 to 120, shortest paths: [['120', '618', '162'], ['120', '621', '162']]
Total paths: 2, num paths: 1
36
df_tmp:  184    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 405, with name:  23 St
Connecting lines: []
From 405 to 120, shortest paths: [['120', '602', '405']]
Total paths: 1, num paths: 1
37
df_tmp:  111    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 616, with name:  74 St-Broadway
Connecting lines: []
From 616 to 120, shortest paths: [['120', '601', '616'], ['120', '618', '616']]
Total paths: 2, num paths: 2
38
df_tmp:  234    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 318, with name:  34 St-Penn Station
Connecting lines: []
From 318 to 120, shortest paths: [['120', '601', '318']]
Total paths: 1, num paths: 1
39
df_tmp:  224    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 165, with name:  23 St
Connecting lines: []
From 165 to 120, shortest paths: [['120', '618', '165'], ['120', '621', '165']]
Total paths: 2, num paths: 1
40
df_tmp:  14    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 307, with name:  116 St-Columbia University
Connecting lines: []
From 307 to 120, shortest paths: [['120', '601', '307']]
Total paths: 1, num paths: 1
41
df_tmp:  119    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 613, with name:  59 St
Connecting lines: []
From 613 to 120, shortest paths: [['120', '602', '613']]
Total paths: 1, num paths: 1
42
df_tmp:  76    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 475, with name:  96 St
Connecting lines: []
From 475 to 120, shortest paths: [['120', '602', '475']]
Total paths: 1, num paths: 1
43
df_tmp:  68    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 625, with name:  Delancey St-Essex St
Connecting lines: []
From 625 to 120, shortest paths: [['120', '601', '625'], ['120', '621', '625']]
Total paths: 2, num paths: 1
44
df_tmp:  3    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 109, with name:  Fresh Pond Rd
Connecting lines: []
From 109 to 120, shortest paths: [['120', '630', '109']]
Total paths: 1, num paths: 0
45
Origin complex id: 310, with name:  96 St
Connecting lines: []
From 310 to 120, shortest paths: [['120', '601', '310']]
Total paths: 1, num paths: 1
46
df_tmp:  319    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 623, with name:  Canal St
Connecting lines: []
From 623 to 120, shortest paths: [['120', '602', '623'], ['120', '621', '623']]
Total paths: 2, num paths: 1
47
df_tmp:  263    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 622, with name:  Brooklyn Bridge-City Hall
Connecting lines: []
From 622 to 120, shortest paths: [['120', '602', '622'], ['120', '621', '622']]
Total paths: 2, num paths: 1
48
df_tmp:  160    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 101, with name:  Marcy Av
Connecting lines: []
From 101 to 120, shortest paths: [['120', '621', '101']]
Total paths: 1, num paths: 0
49
Origin complex id: 240, with name:  7 Av
Connecting lines: []
From 240 to 120, shortest paths: [['120', '601', '240'], ['120', '629', '240']]
Total paths: 2, num paths: 1
50
df_tmp:  114    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 153, with name:  125 St
Connecting lines: []
From 153 to 120, shortest paths: [['120', '618', '153'], ['120', '621', '153']]
Total paths: 2, num paths: 1
51
df_tmp:  235    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 629, with name:  Metropolitan Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
629 is not in stops_before
Origin complex id: 136, with name:  New Lots Av
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
136 is not in stops_before
Origin complex id: 9, with name:  57 St-7 Av
Connecting lines: []
From 9 to 120, shortest paths: [['120', '602', '9']]
Total paths: 1, num paths: 1
54
df_tmp:  0    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 160, with name:  72 St
Connecting lines: []
From 160 to 120, shortest paths: [['120', '618', '160'], ['120', '621', '160']]
Total paths: 2, num paths: 1
55
df_tmp:  311    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 110, with name:  Forest Av
Connecting lines: []
From 110 to 120, shortest paths: [['120', '630', '110']]
Total paths: 1, num paths: 0
56
Origin complex id: 311, with name:  86 St
Connecting lines: []
From 311 to 120, shortest paths: [['120', '601', '311']]
Total paths: 1, num paths: 1
57
df_tmp:  60    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 290, with name:  Classon Av
Connecting lines: []
From 290 to 120, shortest paths: [['120', '629', '290']]
Total paths: 1, num paths: 0
58
Origin complex id: 17, with name:  Prince St
Connecting lines: []
From 17 to 120, shortest paths: [['120', '602', '17']]
Total paths: 1, num paths: 1
59
df_tmp:  255    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 288, with name:  Myrtle-Willoughby Avs
Connecting lines: []
From 288 to 120, shortest paths: [['120', '629', '288']]
Total paths: 1, num paths: 0
60
Origin complex id: 447, with name:  Flushing-Main St
Connecting lines: []
From 447 to 120, shortest paths: [['120', '602', '610', '447'], ['120', '602', '611', '447'], ['120', '601', '611', '447'], ['120', '618', '611', '447'], ['120', '621', '611', '447'], ['120', '602', '461', '447'], ['120', '601', '609', '447'], ['120', '601', '616', '447'], ['120', '618', '616', '447'], ['120', '618', '606', '447'], ['120', '629', '606', '447']]
Total paths: 11, num paths: 9
61
df_tmp:  30    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 223, with name:  Lexington Av/63 St
Connecting lines: []
From 223 to 120, shortest paths: [['120', '602', '223'], ['120', '601', '223']]
Total paths: 2, num paths: 2
62
df_tmp:  259    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 291, with name:  Clinton-Washington Avs
Connecting lines: []
From 291 to 120, shortest paths: [['120', '629', '291']]
Total paths: 1, num paths: 0
63
Origin complex id: 32, with name:  36 St
Connecting lines: []
From 32 to 120, shortest paths: [['120', '602', '32']]
Total paths: 1, num paths: 1
64
df_tmp:  86    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 414, with name:  Bowling Green
Connecting lines: []
From 414 to 120, shortest paths: [['120', '602', '414']]
Total paths: 1, num paths: 1
65
df_tmp:  123    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 44, with name:  Church Av
Connecting lines: []
From 44 to 120, shortest paths: [['120', '602', '44']]
Total paths: 1, num paths: 1
66
df_tmp:  261    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 413, with name:  Wall St
Connecting lines: []
From 413 to 120, shortest paths: [['120', '602', '413']]
Total paths: 1, num paths: 1
67
df_tmp:  105    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 265, with name:  Grand Av-Newtown
Connecting lines: []
From 265 to 120, shortest paths: [['120', '601', '265'], ['120', '618', '265']]
Total paths: 2, num paths: 2
68
df_tmp:  24    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 621, with name:  Broadway Junction
Connecting lines: ['L']
Stops before stop 120: [119, 118, 602, 601, 618]
621 is not in stops_before
Origin complex id: 624, with name:  Park Place
Connecting lines: []
From 624 to 120, shortest paths: [['120', '602', '624'], ['120', '601', '624'], ['120', '618', '624'], ['120', '621', '624']]
Total paths: 4, num paths: 3
70
df_tmp:  302    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 47, with name:  Newkirk Plaza
Connecting lines: []
From 47 to 120, shortest paths: [['120', '602', '47']]
Total paths: 1, num paths: 1
71
df_tmp:  320    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 181, with name:  Utica Av
Connecting lines: []
From 181 to 120, shortest paths: [['120', '618', '181'], ['120', '621', '181']]
Total paths: 2, num paths: 1
72
df_tmp:  314    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 399, with name:  68 St-Hunter College
Connecting lines: []
From 399 to 120, shortest paths: [['120', '602', '399']]
Total paths: 1, num paths: 1
73
df_tmp:  317    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 224, with name:  57 St
Connecting lines: []
From 224 to 120, shortest paths: [['120', '601', '224']]
Total paths: 1, num paths: 1
74
df_tmp:  190    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 94, with name:  Halsey St
Connecting lines: []
From 94 to 120, shortest paths: [['120', '621', '94']]
Total paths: 1, num paths: 0
75
Origin complex id: 404, with name:  28 St
Connecting lines: []
From 404 to 120, shortest paths: [['120', '602', '404']]
Total paths: 1, num paths: 1
76
df_tmp:  305    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 167, with name:  W 4 St-Wash Sq
Connecting lines: []
From 167 to 120, shortest paths: [['120', '601', '167'], ['120', '618', '167'], ['120', '621', '167']]
Total paths: 3, num paths: 2
77
df_tmp:  222    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 396, with name:  96 St
Connecting lines: []
From 396 to 120, shortest paths: [['120', '602', '396']]
Total paths: 1, num paths: 1
78
df_tmp:  50    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 626, with name:  Franklin Av-Medgar Evers College
Connecting lines: []
From 626 to 120, shortest paths: [['120', '602', '626'], ['120', '601', '626']]
Total paths: 2, num paths: 2
79
df_tmp:  185    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 393, with name:  116 St
Connecting lines: []
From 393 to 120, shortest paths: [['120', '602', '393']]
Total paths: 1, num paths: 1
80
df_tmp:  214    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 286, with name:  Broadway
Connecting lines: []
From 286 to 120, shortest paths: [['120', '629', '286']]
Total paths: 1, num paths: 0
81
Origin complex id: 398, with name:  77 St
Connecting lines: []
From 398 to 120, shortest paths: [['120', '602', '398']]
Total paths: 1, num paths: 1
82
df_tmp:  177    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 345, with name:  Crown Hts-Utica Av
Connecting lines: []
From 345 to 120, shortest paths: [['120', '602', '345']]
Total paths: 1, num paths: 1
83
df_tmp:  71    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 10, with name:  49 St
Connecting lines: []
From 10 to 120, shortest paths: [['120', '602', '10']]
Total paths: 1, num paths: 1
84
df_tmp:  171    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 279, with name:  Sutphin Blvd-Archer Av-JFK Airport
Connecting lines: []
From 279 to 120, shortest paths: [['120', '618', '279'], ['120', '621', '279']]
Total paths: 2, num paths: 1
85
df_tmp:  128    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 13, with name:  28 St
Connecting lines: []
From 13 to 120, shortest paths: [['120', '602', '13']]
Total paths: 1, num paths: 1
86
df_tmp:  310    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 409, with name:  Spring St
Connecting lines: []
From 409 to 120, shortest paths: [['120', '602', '409']]
Total paths: 1, num paths: 1
87
df_tmp:  77    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 314, with name:  66 St-Lincoln Center
Connecting lines: []
From 314 to 120, shortest paths: [['120', '601', '314']]
Total paths: 1, num paths: 1
88
df_tmp:  170    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 278, with name:  Jamaica Center-Parsons/Archer
Connecting lines: []
From 278 to 120, shortest paths: [['120', '618', '278'], ['120', '621', '278']]
Total paths: 2, num paths: 1
89
df_tmp:  148    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 395, with name:  103 St
Connecting lines: []
From 395 to 120, shortest paths: [['120', '602', '395']]
Total paths: 1, num paths: 1
90
df_tmp:  1    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 35, with name:  59 St
Connecting lines: []
From 35 to 120, shortest paths: [['120', '602', '35']]
Total paths: 1, num paths: 1
91
df_tmp:  5    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 617, with name:  Atlantic Av-Barclays Ctr
Connecting lines: []
From 617 to 120, shortest paths: [['120', '602', '617'], ['120', '601', '617']]
Total paths: 2, num paths: 2
92
df_tmp:  78    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 228, with name:  23 St
Connecting lines: []
From 228 to 120, shortest paths: [['120', '601', '228']]
Total paths: 1, num paths: 1
93
df_tmp:  282    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 151, with name:  145 St
Connecting lines: []
From 151 to 120, shortest paths: [['120', '618', '151'], ['120', '621', '151']]
Total paths: 2, num paths: 1
94
df_tmp:  25    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 452, with name:  90 St-Elmhurst Av
Connecting lines: []
From 452 to 120, shortest paths: [['120', '602', '610', '452'], ['120', '602', '611', '452'], ['120', '601', '611', '452'], ['120', '618', '611', '452'], ['120', '621', '611', '452'], ['120', '602', '461', '452'], ['120', '601', '609', '452'], ['120', '601', '616', '452'], ['120', '618', '616', '452'], ['120', '618', '606', '452'], ['120', '629', '606', '452']]
Total paths: 11, num paths: 9
95
df_tmp:  138    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 225, with name:  47-50 Sts-Rockefeller Ctr
Connecting lines: []
From 225 to 120, shortest paths: [['120', '601', '225']]
Total paths: 1, num paths: 1
96
df_tmp:  56    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 636, with name:  Jay St-MetroTech
Connecting lines: []
From 636 to 120, shortest paths: [['120', '602', '636'], ['120', '601', '636'], ['120', '618', '636'], ['120', '621', '636']]
Total paths: 4, num paths: 3
97
df_tmp:  94    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 308, with name:  Cathedral Pkwy (110 St)
Connecting lines: []
From 308 to 120, shortest paths: [['120', '601', '308']]
Total paths: 1, num paths: 1
98
df_tmp:  175    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 382, with name:  Fordham Rd
Connecting lines: []
From 382 to 120, shortest paths: [['120', '602', '382']]
Total paths: 1, num paths: 1
99
df_tmp:  106    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 93, with name:  Chauncey St
Connecting lines: []
From 93 to 120, shortest paths: [['120', '621', '93']]
Total paths: 1, num paths: 0
100
Origin complex id: 283, with name:  Greenpoint Av
Connecting lines: []
From 283 to 120, shortest paths: [['120', '629', '283']]
Total paths: 1, num paths: 0
101
Origin complex id: 604, with name:  161 St-Yankee Stadium
Connecting lines: []
From 604 to 120, shortest paths: [['120', '602', '604']]
Total paths: 1, num paths: 1
102
df_tmp:  301    120
Name: destination_station_complex_id, dtype: int64
Origin complex id: 450, with name:  103 St-Corona Plaza
Connecting lines: []
From 450 to 120, shortest paths: [['120', '602', '610', '450'], ['120', '602', '611', '450'], ['120', '601', '611', '450'], ['120', '618', '611', '450'], ['120', '621', '611', '450'], ['120', '602', '461', '450'], ['120', '601', '609', '450'], ['120', '601', '616', '450'], ['120', '618', '616', '450'], ['120', '618', '606', '450'], ['120', '629', '606', '450']]

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,9,Monday,10,119,1 Av (L),120,Bedford Av (L),61.32780
1,2025,9,Monday,10,602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",120,Bedford Av (L),42.74880
2,2025,9,Monday,10,611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",120,Bedford Av (L),24.25305
3,2025,9,Monday,10,601,"14 St (F,M,1,2,3)/6 Av (L)",120,Bedford Av (L),32.01140
4,2025,9,Monday,10,164,"34 St-Penn Station (A,C,E)",120,Bedford Av (L),14.38670
...,...,...,...,...,...,...,...,...,...
269,2025,9,Monday,10,241,"15 St-Prospect Park (F,G)",120,Bedford Av (L),0.11140
270,2025,9,Monday,10,334,"Clark St (2,3)",120,Bedford Av (L),0.22080
271,2025,9,Monday,10,145,190 St (A),120,Bedford Av (L),0.11010
272,2025,9,Monday,10,303,157 St (1),120,Bedford Av (L),0.21960
273,2025,9,Monday,10,294,238 St (1),120,Bedford Av (L),0.20000

In [15]:
# 0 = north/east-bound, 1 = south/west-bound
print(get_ordered_stops("L", 1))

{'8 Av': 618, '6 Av': 601, '14 St-Union Sq': 602, '3 Av': 118, '1 Av': 119, 'Bedford Av': 120, 'Lorimer St': 629, 'Graham Av': 122, 'Grand St': 123, 'Montrose Av': 124, 'Morgan Av': 125, 'Jefferson St': 126, 'DeKalb Av': 127, 'Myrtle-Wyckoff Avs': 630, 'Halsey St': 129, 'Wilson Av': 130, 'Bushwick Av-Aberdeen St': 131, 'Broadway Junction': 621, 'Atlantic Av': 133, 'Sutter Av': 134, 'Livonia Av': 135, 'New Lots Av': 136, 'East 105 St': 137, 'Canarsie-Rockaway Pkwy': 138}

In [16]:
from socrata_od_client import get_ridership_data

complex_id = "118"
line = "L"
direction = 1 # 0 = north/east-bound (towards 8 Av), 1 = south/west-bound (towards Rockaway)

year = 2025
month = 9
day_of_week = "Monday"
hour_of_day = "9"

# Get weekday ridership for May 2024 at 9am from station 623
df_onboards = get_onboards_data(complex_id, year, month, day_of_week, hour_of_day)
df_offboards = get_offboards_data(complex_id, year, month, day_of_week, hour_of_day)


obs_onboard, df_onboard = get_onboardings (complex_id, line, direction, df_onboards)
obs_offboard, df_offboard = get_offboardings (complex_id, line, direction, df_offboards)

Destination complex id: 120
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
120 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 618
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
618 is not in stops_after

Destination complex id: 122
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
122 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 164
Connecting lines: []
From 118 to 164, shortest paths: [['118', '618', '164'], ['118', '621', '164']]
Total paths: 2, num paths: 1
3
df_tmp:  35    164
Name: destination_station_complex_id, dtype: int64

Destination complex id: 601
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
601 is not in stops_after

Destination complex id: 629
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
629 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 607
Connecting lines: []
From 118 to 607, shortest paths: [['118', '602', '607'], ['118', '601', '607']]
Total paths: 2, num paths: 0
6

Destination complex id: 611
Connecting lines: []
From 118 to 611, shortest paths: [['118', '602', '611'], ['118', '601', '611'], ['118', '618', '611'], ['118', '621', '611']]
Total paths: 4, num paths: 1
7
df_tmp:  100    611
Name: destination_station_complex_id, dtype: int64

Destination complex id: 324
Connecting lines: []
From 118 to 324, shortest paths: [['118', '601', '324']]
Total paths: 1, num paths: 0
8

Destination complex id: 225
Connecting lines: []
From 118 to 225, shortest paths: [['118', '601', '225']]
Total paths: 1, num paths: 0
9

Destination complex id: 138
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
138 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 283
Connecting lines: []
From 118 to 283, shortest paths: [['118', '629', '283']]
Total paths: 1, num paths: 1
11
df_tmp:  125    283
Name: destination_station_complex_id, dtype: int64

Destination complex id: 168
Connecting lines: []
From 118 to 168, shortest paths: [['118', '618', '168'], ['118', '621', '168']]
Total paths: 2, num paths: 1
12
df_tmp:  90    168
Name: destination_station_complex_id, dtype: int64

Destination complex id: 127
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
127 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 10
Connecting lines: []
From 118 to 10, shortest paths: [['118', '602', '10']]
Total paths: 1, num paths: 0
14

Destination complex id: 327
Connecting lines: []
From 118 to 327, shortest paths: [['118', '601', '327']]
Total paths: 1, num paths: 0
15

Destination complex id: 609
Connecting lines: []
From 118 to 609, shortest paths: [['118', '601', '609']]
Total paths: 1, num paths: 0
16

Destination complex id: 129
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
129 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 307
Connecting lines: []
From 118 to 307, shortest paths: [['118', '601', '307']]
Total paths: 1, num paths: 0
18

Destination complex id: 165
Connecting lines: []
From 118 to 165, shortest paths: [['118', '618', '165'], ['118', '621', '165']]
Total paths: 2, num paths: 1
19
df_tmp:  38    165
Name: destination_station_complex_id, dtype: int64

Destination complex id: 125
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
125 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 610
Connecting lines: []
From 118 to 610, shortest paths: [['118', '602', '610']]
Total paths: 1, num paths: 0
21

Destination complex id: 235
Connecting lines: []
From 118 to 235, shortest paths: [['118', '601', '235']]
Total paths: 1, num paths: 0
22

Destination complex id: 126
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
126 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 123
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
123 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 16
Connecting lines: []
From 118 to 16, shortest paths: [['118', '602', '16']]
Total paths: 1, num paths: 0
25

Destination complex id: 636
Connecting lines: []
From 118 to 636, shortest paths: [['118', '602', '636'], ['118', '601', '636'], ['118', '618', '636'], ['118', '621', '636']]
Total paths: 4, num paths: 1
26
df_tmp:  57    636
Name: destination_station_complex_id, dtype: int64

Destination complex id: 314
Connecting lines: []
From 118 to 314, shortest paths: [['118', '601', '314']]
Total paths: 1, num paths: 0
27

Destination complex id: 630
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
630 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 289
Connecting lines: []
From 118 to 289, shortest paths: [['118', '629', '289']]
Total paths: 1, num paths: 1
29
df_tmp:  37    289
Name: destination_station_complex_id, dtype: int64

Destination complex id: 101
Connecting lines: []
From 118 to 101, shortest paths: [['118', '621', '101']]
Total paths: 1, num paths: 1
30
df_tmp:  47    101
Name: destination_station_complex_id, dtype: int64

Destination complex id: 614
Connecting lines: []
From 118 to 614, shortest paths: [['118', '601', '614'], ['118', '618', '614'], ['118', '621', '614']]
Total paths: 3, num paths: 1
31
df_tmp:  77    614
Name: destination_station_complex_id, dtype: int64

Destination complex id: 602
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
602 is not in stops_after

Destination complex id: 623
Connecting lines: []
From 118 to 623, shortest paths: [['118', '602', '623'], ['118', '621', '623']]
Total paths: 2, num paths: 1
33
df_tmp:  44    623
Name: destination_station_complex_id, dtype: int64

Destination complex id: 313
Connecting lines: []
From 118 to 313, shortest paths: [['118', '601', '313']]
Total paths: 1, num paths: 0
34

Destination complex id: 119
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
119 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 605
Connecting lines: []
From 118 to 605, shortest paths: [['118', '601', '605'], ['118', '618', '605'], ['118', '621', '605']]
Total paths: 3, num paths: 1
36
df_tmp:  46    605
Name: destination_station_complex_id, dtype: int64

Destination complex id: 159
Connecting lines: []
From 118 to 159, shortest paths: [['118', '618', '159'], ['118', '621', '159']]
Total paths: 2, num paths: 1
37
df_tmp:  102    159
Name: destination_station_complex_id, dtype: int64

Destination complex id: 624
Connecting lines: []
From 118 to 624, shortest paths: [['118', '602', '624'], ['118', '601', '624'], ['118', '618', '624'], ['118', '621', '624']]
Total paths: 4, num paths: 1
38
df_tmp:  106    624
Name: destination_station_complex_id, dtype: int64

Destination complex id: 619
Connecting lines: []
From 118 to 619, shortest paths: [['118', '602', '619'], ['118', '601', '619']]
Total paths: 2, num paths: 0
39

Destination complex id: 306
Connecting lines: []
From 118 to 306, shortest paths: [['118', '601', '306']]
Total paths: 1, num paths: 0
40

Destination complex id: 288
Connecting lines: []
From 118 to 288, shortest paths: [['118', '629', '288']]
Total paths: 1, num paths: 1
41
df_tmp:  22    288
Name: destination_station_complex_id, dtype: int64

Destination complex id: 284
Connecting lines: []
From 118 to 284, shortest paths: [['118', '629', '284']]
Total paths: 1, num paths: 1
42
df_tmp:  122    284
Name: destination_station_complex_id, dtype: int64

Destination complex id: 124
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
124 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 137
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
137 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 309
Connecting lines: []
From 118 to 309, shortest paths: [['118', '601', '309']]
Total paths: 1, num paths: 0
45

Destination complex id: 606
Connecting lines: []
From 118 to 606, shortest paths: [['118', '618', '606'], ['118', '629', '606']]
Total paths: 2, num paths: 1
46
df_tmp:  52    606
Name: destination_station_complex_id, dtype: int64

Destination complex id: 318
Connecting lines: []
From 118 to 318, shortest paths: [['118', '601', '318']]
Total paths: 1, num paths: 0
47

Destination complex id: 448
Connecting lines: []
From 118 to 448, shortest paths: [['118', '602', '610', '448'], ['118', '602', '611', '448'], ['118', '601', '611', '448'], ['118', '618', '611', '448'], ['118', '621', '611', '448'], ['118', '602', '461', '448'], ['118', '601', '609', '448'], ['118', '601', '616', '448'], ['118', '618', '616', '448'], ['118', '618', '606', '448'], ['118', '629', '606', '448']]
Total paths: 11, num paths: 2
48
df_tmp:  87    448
Name: destination_station_complex_id, dtype: int64

Destination complex id: 162
Connecting lines: []
From 118 to 162, shortest paths: [['118', '618', '162'], ['118', '621', '162']]
Total paths: 2, num paths: 1
49
df_tmp:  56    162
Name: destination_station_complex_id, dtype: int64

Destination complex id: 326
Connecting lines: []
From 118 to 326, shortest paths: [['118', '601', '326']]
Total paths: 1, num paths: 0
50

Destination complex id: 167
Connecting lines: []
From 118 to 167, shortest paths: [['118', '601', '167'], ['118', '618', '167'], ['118', '621', '167']]
Total paths: 3, num paths: 1
51
df_tmp:  62    167
Name: destination_station_complex_id, dtype: int64

Destination complex id: 407
Connecting lines: []
From 118 to 407, shortest paths: [['118', '602', '407']]
Total paths: 1, num paths: 0
52

Destination complex id: 622
Connecting lines: []
From 118 to 622, shortest paths: [['118', '602', '622'], ['118', '621', '622']]
Total paths: 2, num paths: 1
53
df_tmp:  27    622
Name: destination_station_complex_id, dtype: int64

Destination complex id: 136
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
136 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 290
Connecting lines: []
From 118 to 290, shortest paths: [['118', '629', '290']]
Total paths: 1, num paths: 1
55
df_tmp:  31    290
Name: destination_station_complex_id, dtype: int64

Destination complex id: 413
Connecting lines: []
From 118 to 413, shortest paths: [['118', '602', '413']]
Total paths: 1, num paths: 0
56

Destination complex id: 261
Connecting lines: []
From 118 to 261, shortest paths: [['118', '601', '261'], ['118', '618', '261']]
Total paths: 2, num paths: 0
57

Destination complex id: 441
Connecting lines: []
From 118 to 441, shortest paths: [['118', '601', '441']]
Total paths: 1, num paths: 0
58

Destination complex id: 276
Connecting lines: []
From 118 to 276, shortest paths: [['118', '618', '276']]
Total paths: 1, num paths: 0
59

Destination complex id: 405
Connecting lines: []
From 118 to 405, shortest paths: [['118', '602', '405']]
Total paths: 1, num paths: 0
60

Destination complex id: 188
Connecting lines: []
From 118 to 188, shortest paths: [['118', '618', '188'], ['118', '621', '188']]
Total paths: 2, num paths: 1
61
df_tmp:  97    188
Name: destination_station_complex_id, dtype: int64

Destination complex id: 399
Connecting lines: []
From 118 to 399, shortest paths: [['118', '602', '399']]
Total paths: 1, num paths: 0
62

Destination complex id: 169
Connecting lines: []
From 118 to 169, shortest paths: [['118', '618', '169'], ['118', '621', '169']]
Total paths: 2, num paths: 1
63
df_tmp:  68    169
Name: destination_station_complex_id, dtype: int64

Destination complex id: 113
Connecting lines: []
From 118 to 113, shortest paths: [['118', '630', '113']]
Total paths: 1, num paths: 1
64
df_tmp:  83    113
Name: destination_station_complex_id, dtype: int64

Destination complex id: 617
Connecting lines: []
From 118 to 617, shortest paths: [['118', '602', '617'], ['118', '601', '617']]
Total paths: 2, num paths: 0
65

Destination complex id: 94
Connecting lines: []
From 118 to 94, shortest paths: [['118', '621', '94']]
Total paths: 1, num paths: 1
66
df_tmp:  30    94
Name: destination_station_complex_id, dtype: int64

Destination complex id: 278
Connecting lines: []
From 118 to 278, shortest paths: [['118', '618', '278'], ['118', '621', '278']]
Total paths: 2, num paths: 1
67
df_tmp:  98    278
Name: destination_station_complex_id, dtype: int64

Destination complex id: 83
Connecting lines: []
From 118 to 83, shortest paths: [['118', '621', '83']]
Total paths: 1, num paths: 1
68
df_tmp:  6    83
Name: destination_station_complex_id, dtype: int64

Destination complex id: 628
Connecting lines: []
From 118 to 628, shortest paths: [['118', '602', '628'], ['118', '601', '628'], ['118', '618', '628'], ['118', '621', '628']]
Total paths: 4, num paths: 1
69
df_tmp:  104    628
Name: destination_station_complex_id, dtype: int64

Destination complex id: 621
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
621 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 111
Connecting lines: []
From 118 to 111, shortest paths: [['118', '630', '111']]
Total paths: 1, num paths: 1
71
df_tmp:  73    111
Name: destination_station_complex_id, dtype: int64

Destination complex id: 87
Connecting lines: []
From 118 to 87, shortest paths: [['118', '621', '87']]
Total paths: 1, num paths: 1
72
df_tmp:  133    87
Name: destination_station_complex_id, dtype: int64

Destination complex id: 181
Connecting lines: []
From 118 to 181, shortest paths: [['118', '618', '181'], ['118', '621', '181']]
Total paths: 2, num paths: 1
73
df_tmp:  41    181
Name: destination_station_complex_id, dtype: int64

Destination complex id: 135
Connecting lines: ['L']
Stops after stop 118: [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]
135 is in [119, 120, 629, 122, 123, 124, 125, 126, 127, 630, 129, 130, 131, 621, 133, 134, 135, 136, 137, 138]

Destination complex id: 59
Connecting lines: []
From 118 to 59, shortest paths: [['118', '602', '604', '59'], ['118', '602', '619', '59'], ['118', '601', '619', '59'], ['118', '602', '617', '59'], ['118', '601', '617', '59'], ['118', '602', '607', '59'], ['118', '601', '607', '59'], ['118', '602', '26', '59'], ['118', '602', '28', '59'], ['118', '602', '608', '59'], ['118', '601', '608', '59'], ['118', '629', '608', '59'], ['118', '602', '30', '59'], ['118', '602', '31', '59'], ['118', '602', '32', '59'], ['118', '602', '615', '59'], ['118', '602', '58', '59'], ['118', '601', '58', '59'], ['118', '601', '614', '59'], ['118', '618', '614', '59'], ['118', '621', '614', '59'], ['118', '601', '609', '59'], ['118', '601', '225', '59'], ['118', '601', '167', '59'], ['118', '618', '167', '59'], ['118', '621', '167', '59'], ['118', '618', '153', '59'], ['118', '621', '153', '59'], ['118', '618', '151', '59'], ['118', '621', '151', '59'], ['118', '618', '277', '59']]
Total paths: 31, num paths: 5
75
df_tmp:  120    59
Name: destination_station_complex_id, dtype: int64

Destination complex id: 224
Connecting lines: []
From 118 to 224, shortest paths: [['118', '601', '224']]
Total paths: 1, num paths: 0
76

Destination complex id: 153
Connecting lines: []
From 118 to 153, shortest paths: [['118', '618', '153'], ['118', '621', '153']]
Total paths: 2, num paths: 1
77
df_tmp:  19    153
Name: destination_station_complex_id, dtype: int64

Destination complex id: 9
Connecting lines: []
From 118 to 9, shortest paths: [['118', '602', '9']]
Total paths: 1, num paths: 0
78

Destination complex id: 154
Connecting lines: []
From 118 to 154, shortest paths: [['118', '618', '154'], ['118', '621', '154']]
Total paths: 2, num paths: 1
79
df_tmp:  99    154
Name: destination_station_complex_id, dtype: int64

Destination complex id: 424
Connecting lines: []
From 118 to 424, shortest paths: [['118', '601', '424']]
Total paths: 1, num paths: 0
80

Destination complex id: 612
Connecting lines: []
From 118 to 612, shortest paths: [['118', '602', '612'], ['118', '618', '612']]
Total paths: 2, num paths: 0
81

Destination complex id: 396
Connecting lines: []
From 118 to 396, shortest paths: [['118', '602', '396']]
Total paths: 1, num paths: 0
82

Destination complex id: 319
Connecting lines: []
From 118 to 319, shortest paths: [['118', '601', '319']]
Total paths: 1, num paths: 0
83

Destination complex id: 35
Connecting lines: []
From 118 to 35, shortest paths: [['118', '602', '35']]
Total paths: 1, num paths: 0
84

Destination complex id: 393
Connecting lines: []
From 118 to 393, shortest paths: [['118', '602', '393']]
Total paths: 1, num paths: 0
85

Destination complex id: 360
Connecting lines: []
From 118 to 360, shortest paths: [['118', '602', '360']]
Total paths: 1, num paths: 0
86

Destination complex id: 613
Connecting lines: []
From 118 to 613, shortest paths: [['118', '602', '613']]
Total paths: 1, num paths: 0
87

Destination complex id: 626
Connecting lines: []
From 118 to 626, shortest paths: [['118', '602', '626'], ['118', '601', '626']]
Total paths: 2, num paths: 0
88

Destination complex id: 160
Connecting lines: []
From 118 to 160, shortest paths: [['118', '618', '160'], ['118', '621', '160']]
Total paths: 2, num paths: 1
89
df_tmp:  127    160
Name: destination_station_complex_id, dtype: int64

Destination complex id: 382
Connecting lines: []
From 118 to 382, shortest paths: [['118', '602', '382']]
Total paths: 1, num paths: 0
90

Destination complex id: 234
Connecting lines: []
From 118 to 234, shortest paths: [['118', '601', '234']]
Total paths: 1, num paths: 0
91

Destination complex id: 398
Connecting lines: []
From 118 to 398, shortest paths: [['118', '602', '398']]
Total paths: 1, num paths: 0
92


/var/folders/vv/8v01rf7n71748vxd0m5kt_dr0000gn/T/ipykernel_97437/4148522952.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)

Stops before stop 118: [602, 601, 618]
127 is not in stops_before
Origin complex id: 122, with name:  Graham Av
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
122 is not in stops_before
Origin complex id: 124, with name:  Montrose Av
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
124 is not in stops_before
Origin complex id: 126, with name:  Jefferson St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
126 is not in stops_before
Origin complex id: 125, with name:  Morgan Av
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
125 is not in stops_before
Origin complex id: 129, with name:  Halsey St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
129 is not in stops_before
Origin complex id: 283, with name:  Greenpoint Av
Connecting lines: []
From 283 to 118, shortest paths: [['118', '629', '283']]
Total paths: 1, num paths: 0
9
Origin complex id: 289, with name:  Bedford-Nostrand Avs
Connecting lines: []
From 289 to 118, shortest paths: [['118', '629', '289']]
Total paths: 1, num paths: 0
10
Origin complex id: 123, with name:  Grand St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
123 is not in stops_before
Origin complex id: 611, with name:  Times Sq-42 St
Connecting lines: []
From 611 to 118, shortest paths: [['118', '602', '611'], ['118', '601', '611'], ['118', '618', '611'], ['118', '621', '611']]
Total paths: 4, num paths: 3
12
df_tmp:  130    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 136, with name:  New Lots Av
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
136 is not in stops_before
Origin complex id: 130, with name:  Wilson Av
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
130 is not in stops_before
Origin complex id: 138, with name:  Canarsie-Rockaway Pkwy
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
138 is not in stops_before
Origin complex id: 164, with name:  34 St-Penn Station
Connecting lines: []
From 164 to 118, shortest paths: [['118', '618', '164'], ['118', '621', '164']]
Total paths: 2, num paths: 1
16
df_tmp:  5    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 601, with name:  14 St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
601 is in [602, 601, 618]
Origin complex id: 290, with name:  Classon Av
Connecting lines: []
From 290 to 118, shortest paths: [['118', '629', '290']]
Total paths: 1, num paths: 0
18
Origin complex id: 618, with name:  14 St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
618 is in [602, 601, 618]
Origin complex id: 97, with name:  Myrtle Av
Connecting lines: []
From 97 to 118, shortest paths: [['118', '630', '97'], ['118', '621', '97']]
Total paths: 2, num paths: 0
20
Origin complex id: 131, with name:  Bushwick Av-Aberdeen St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
131 is not in stops_before
Origin complex id: 288, with name:  Myrtle-Willoughby Avs
Connecting lines: []
From 288 to 118, shortest paths: [['118', '629', '288']]
Total paths: 1, num paths: 0
22
Origin complex id: 610, with name:  Grand Central-42 St
Connecting lines: []
From 610 to 118, shortest paths: [['118', '602', '610']]
Total paths: 1, num paths: 1
23
df_tmp:  118    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 447, with name:  Flushing-Main St
Connecting lines: []
From 447 to 118, shortest paths: [['118', '602', '610', '447'], ['118', '602', '611', '447'], ['118', '601', '611', '447'], ['118', '618', '611', '447'], ['118', '621', '611', '447'], ['118', '602', '461', '447'], ['118', '601', '609', '447'], ['118', '601', '616', '447'], ['118', '618', '616', '447'], ['118', '618', '606', '447'], ['118', '629', '606', '447']]
Total paths: 11, num paths: 9
24
df_tmp:  120    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 279, with name:  Sutphin Blvd-Archer Av-JFK Airport
Connecting lines: []
From 279 to 118, shortest paths: [['118', '618', '279'], ['118', '621', '279']]
Total paths: 2, num paths: 1
25
df_tmp:  16    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 151, with name:  145 St
Connecting lines: []
From 151 to 118, shortest paths: [['118', '618', '151'], ['118', '621', '151']]
Total paths: 2, num paths: 1
26
df_tmp:  180    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 109, with name:  Fresh Pond Rd
Connecting lines: []
From 109 to 118, shortest paths: [['118', '630', '109']]
Total paths: 1, num paths: 0
27
Origin complex id: 310, with name:  96 St
Connecting lines: []
From 310 to 118, shortest paths: [['118', '601', '310']]
Total paths: 1, num paths: 1
28
df_tmp:  30    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 119, with name:  1 Av
Connecting lines: ['L']

/var/folders/vv/8v01rf7n71748vxd0m5kt_dr0000gn/T/ipykernel_97437/1818246956.py:64: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  boardings_df =  pd.concat([boardings_df, df_tmp], ignore_index=True)

Stops before stop 118: [602, 601, 618]
119 is not in stops_before
Origin complex id: 71, with name:  8 Av
Connecting lines: []
From 71 to 118, shortest paths: [['118', '602', '71']]
Total paths: 1, num paths: 1
30
df_tmp:  114    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 607, with name:  34 St-Herald Sq
Connecting lines: []
From 607 to 118, shortest paths: [['118', '602', '607'], ['118', '601', '607']]
Total paths: 2, num paths: 2
31
df_tmp:  115    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 195, with name:  Ozone Park-Lefferts Blvd
Connecting lines: []
From 195 to 118, shortest paths: [['118', '618', '195'], ['118', '621', '195']]
Total paths: 2, num paths: 1
32
df_tmp:  10    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 83, with name:  Woodhaven Blvd
Connecting lines: []
From 83 to 118, shortest paths: [['118', '621', '83']]
Total paths: 1, num paths: 0
33
Origin complex id: 165, with name:  23 St
Connecting lines: []
From 165 to 118, shortest paths: [['118', '618', '165'], ['118', '621', '165']]
Total paths: 2, num paths: 1
34
df_tmp:  33    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 188, with name:  Euclid Av
Connecting lines: []
From 188 to 118, shortest paths: [['118', '618', '188'], ['118', '621', '188']]
Total paths: 2, num paths: 1
35
df_tmp:  205    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 98, with name:  Flushing Av
Connecting lines: []
From 98 to 118, shortest paths: [['118', '621', '98']]
Total paths: 1, num paths: 0
36
Origin complex id: 33, with name:  45 St
Connecting lines: []
From 33 to 118, shortest paths: [['118', '602', '33']]
Total paths: 1, num paths: 1
37
df_tmp:  207    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 108, with name:  Middle Village-Metropolitan Av
Connecting lines: []
From 108 to 118, shortest paths: [['118', '630', '108']]
Total paths: 1, num paths: 0
38
Origin complex id: 617, with name:  Atlantic Av-Barclays Ctr
Connecting lines: []
From 617 to 118, shortest paths: [['118', '602', '617'], ['118', '601', '617']]
Total paths: 2, num paths: 2
39
df_tmp:  106    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 10, with name:  49 St
Connecting lines: []
From 10 to 118, shortest paths: [['118', '602', '10']]
Total paths: 1, num paths: 1
40
df_tmp:  208    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 313, with name:  72 St
Connecting lines: []
From 313 to 118, shortest paths: [['118', '601', '313']]
Total paths: 1, num paths: 1
41
df_tmp:  82    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 156, with name:  103 St
Connecting lines: []
From 156 to 118, shortest paths: [['118', '618', '156'], ['118', '621', '156']]
Total paths: 2, num paths: 1
42
df_tmp:  123    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 284, with name:  Nassau Av
Connecting lines: []
From 284 to 118, shortest paths: [['118', '629', '284']]
Total paths: 1, num paths: 0
43
Origin complex id: 16, with name:  8 St-NYU
Connecting lines: []
From 16 to 118, shortest paths: [['118', '602', '16']]
Total paths: 1, num paths: 1
44
df_tmp:  69    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 318, with name:  34 St-Penn Station
Connecting lines: []
From 318 to 118, shortest paths: [['118', '601', '318']]
Total paths: 1, num paths: 1
45
df_tmp:  68    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 626, with name:  Franklin Av-Medgar Evers College
Connecting lines: []
From 626 to 118, shortest paths: [['118', '602', '626'], ['118', '601', '626']]
Total paths: 2, num paths: 2
46
df_tmp:  128    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 605, with name:  168 St-Washington Hts
Connecting lines: []
From 605 to 118, shortest paths: [['118', '601', '605'], ['118', '618', '605'], ['118', '621', '605']]
Total paths: 3, num paths: 2
47
df_tmp:  48    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 291, with name:  Clinton-Washington Avs
Connecting lines: []
From 291 to 118, shortest paths: [['118', '629', '291']]
Total paths: 1, num paths: 0
48
Origin complex id: 110, with name:  Forest Av
Connecting lines: []
From 110 to 118, shortest paths: [['118', '630', '110']]
Total paths: 1, num paths: 0
49
Origin complex id: 621, with name:  Broadway Junction
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
621 is not in stops_before
Origin complex id: 84, with name:  85 St-Forest Pkwy
Connecting lines: []
From 84 to 118, shortest paths: [['118', '621', '84']]
Total paths: 1, num paths: 0
51
Origin complex id: 403, with name:  33 St
Connecting lines: []
From 403 to 118, shortest paths: [['118', '602', '403']]
Total paths: 1, num paths: 1
52
df_tmp:  146    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 257, with name:  Sutphin Blvd
Connecting lines: []
From 257 to 118, shortest paths: [['118', '601', '257']]
Total paths: 1, num paths: 1
53
df_tmp:  192    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 287, with name:  Flushing Av
Connecting lines: []
From 287 to 118, shortest paths: [['118', '629', '287']]
Total paths: 1, num paths: 0
54
Origin complex id: 9, with name:  57 St-7 Av
Connecting lines: []
From 9 to 118, shortest paths: [['118', '602', '9']]
Total paths: 1, num paths: 1
55
df_tmp:  42    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 612, with name:  51 St
Connecting lines: []
From 612 to 118, shortest paths: [['118', '602', '612'], ['118', '618', '612']]
Total paths: 2, num paths: 2
56
df_tmp:  20    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 303, with name:  157 St
Connecting lines: []
From 303 to 118, shortest paths: [['118', '601', '303']]
Total paths: 1, num paths: 1
57
df_tmp:  166    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 155, with name:  Cathedral Pkwy (110 St)
Connecting lines: []
From 155 to 118, shortest paths: [['118', '618', '155'], ['118', '621', '155']]
Total paths: 2, num paths: 1
58
df_tmp:  116    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 286, with name:  Broadway
Connecting lines: []
From 286 to 118, shortest paths: [['118', '629', '286']]
Total paths: 1, num paths: 0
59
Origin complex id: 26, with name:  DeKalb Av
Connecting lines: []
From 26 to 118, shortest paths: [['118', '602', '26']]
Total paths: 1, num paths: 1
60
df_tmp:  64    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 1, with name:  Astoria-Ditmars Blvd
Connecting lines: []
From 1 to 118, shortest paths: [['118', '602', '1']]
Total paths: 1, num paths: 1
61
df_tmp:  97    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 44, with name:  Church Av
Connecting lines: []
From 44 to 118, shortest paths: [['118', '602', '44']]
Total paths: 1, num paths: 1
62
df_tmp:  6    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 404, with name:  28 St
Connecting lines: []
From 404 to 118, shortest paths: [['118', '602', '404']]
Total paths: 1, num paths: 1
63
df_tmp:  47    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 113, with name:  Knickerbocker Av
Connecting lines: []
From 113 to 118, shortest paths: [['118', '630', '113']]
Total paths: 1, num paths: 0
64
Origin complex id: 38, with name:  86 St
Connecting lines: []
From 38 to 118, shortest paths: [['118', '602', '620', '38'], ['118', '601', '620', '38'], ['118', '602', '617', '38'], ['118', '601', '617', '38'], ['118', '602', '635', '38'], ['118', '601', '635', '38'], ['118', '602', '636', '38'], ['118', '601', '636', '38'], ['118', '618', '636', '38'], ['118', '621', '636', '38'], ['118', '602', '26', '38'], ['118', '602', '28', '38'], ['118', '602', '608', '38'], ['118', '601', '608', '38'], ['118', '629', '608', '38'], ['118', '602', '30', '38'], ['118', '602', '31', '38'], ['118', '602', '32', '38'], ['118', '602', '33', '38'], ['118', '602', '34', '38'], ['118', '602', '35', '38']]
Total paths: 21, num paths: 19
65
df_tmp:  155    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 300, with name:  191 St
Connecting lines: []
From 300 to 118, shortest paths: [['118', '601', '300']]
Total paths: 1, num paths: 1
66
df_tmp:  202    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 405, with name:  23 St
Connecting lines: []
From 405 to 118, shortest paths: [['118', '602', '405']]
Total paths: 1, num paths: 1
67
df_tmp:  184    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 74, with name:  18 Av
Connecting lines: []
From 74 to 118, shortest paths: [['118', '602', '74']]
Total paths: 1, num paths: 1
68
df_tmp:  119    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 85, with name:  75 St-Elderts Ln
Connecting lines: []
From 85 to 118, shortest paths: [['118', '621', '85']]
Total paths: 1, num paths: 0
69
Origin complex id: 143, with name:  Inwood-207 St
Connecting lines: []
From 143 to 118, shortest paths: [['118', '618', '143'], ['118', '621', '143']]
Total paths: 2, num paths: 1
70
df_tmp:  137    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 66, with name:  18 Av
Connecting lines: []
From 66 to 118, shortest paths: [['118', '602', '604', '66'], ['118', '602', '619', '66'], ['118', '601', '619', '66'], ['118', '602', '617', '66'], ['118', '601', '617', '66'], ['118', '602', '607', '66'], ['118', '601', '607', '66'], ['118', '602', '26', '66'], ['118', '602', '28', '66'], ['118', '602', '608', '66'], ['118', '601', '608', '66'], ['118', '629', '608', '66'], ['118', '602', '30', '66'], ['118', '602', '31', '66'], ['118', '602', '32', '66'], ['118', '602', '615', '66'], ['118', '602', '58', '66'], ['118', '601', '58', '66'], ['118', '601', '614', '66'], ['118', '618', '614', '66'], ['118', '621', '614', '66'], ['118', '601', '609', '66'], ['118', '601', '225', '66'], ['118', '601', '167', '66'], ['118', '618', '167', '66'], ['118', '621', '167', '66'], ['118', '618', '153', '66'], ['118', '621', '153', '66'], ['118', '618', '151', '66'], ['118', '621', '151', '66'], ['118', '618', '277', '66']]
Total paths: 31, num paths: 26
71
df_tmp:  188    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 255, with name:  169 St
Connecting lines: []
From 255 to 118, shortest paths: [['118', '601', '255']]
Total paths: 1, num paths: 1
72
df_tmp:  70    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 101, with name:  Marcy Av
Connecting lines: []
From 101 to 118, shortest paths: [['118', '621', '101']]
Total paths: 1, num paths: 0
73
Origin complex id: 259, with name:  Kew Gardens-Union Tpke
Connecting lines: []
From 259 to 118, shortest paths: [['118', '601', '259'], ['118', '618', '259']]
Total paths: 2, num paths: 2
74
df_tmp:  145    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 453, with name:  82 St-Jackson Hts
Connecting lines: []
From 453 to 118, shortest paths: [['118', '602', '610', '453'], ['118', '602', '611', '453'], ['118', '601', '611', '453'], ['118', '618', '611', '453'], ['118', '621', '611', '453'], ['118', '602', '461', '453'], ['118', '601', '609', '453'], ['118', '601', '616', '453'], ['118', '618', '616', '453'], ['118', '618', '606', '453'], ['118', '629', '606', '453']]
Total paths: 11, num paths: 9
75
df_tmp:  178    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 235, with name:  York St
Connecting lines: []
From 235 to 118, shortest paths: [['118', '601', '235']]
Total paths: 1, num paths: 1
76
df_tmp:  0    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 261, with name:  Forest Hills-71 Av
Connecting lines: []
From 261 to 118, shortest paths: [['118', '601', '261'], ['118', '618', '261']]
Total paths: 2, num paths: 2
77
df_tmp:  78    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 114, with name:  Central Av
Connecting lines: []
From 114 to 118, shortest paths: [['118', '630', '114']]
Total paths: 1, num paths: 0
78
Origin complex id: 258, with name:  Briarwood
Connecting lines: []
From 258 to 118, shortest paths: [['118', '601', '258'], ['118', '618', '258']]
Total paths: 2, num paths: 2
79
df_tmp:  185    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 207, with name:  Beach 36 St
Connecting lines: []
From 207 to 118, shortest paths: []
Total paths: 0, num paths: 0
80
Origin complex id: 371, with name:  Hunts Point Av
Connecting lines: []
From 371 to 118, shortest paths: [['118', '602', '371']]
Total paths: 1, num paths: 1
81
df_tmp:  51    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 414, with name:  Bowling Green
Connecting lines: []
From 414 to 118, shortest paths: [['118', '602', '414']]
Total paths: 1, num paths: 1
82
df_tmp:  127    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 162, with name:  50 St
Connecting lines: []
From 162 to 118, shortest paths: [['118', '618', '162'], ['118', '621', '162']]
Total paths: 2, num paths: 1
83
df_tmp:  121    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 407, with name:  Astor Pl
Connecting lines: []
From 407 to 118, shortest paths: [['118', '602', '407']]
Total paths: 1, num paths: 1
84
df_tmp:  138    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 619, with name:  Bleecker St
Connecting lines: []
From 619 to 118, shortest paths: [['118', '602', '619'], ['118', '601', '619']]
Total paths: 2, num paths: 2
85
df_tmp:  142    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 309, with name:  103 St
Connecting lines: []
From 309 to 118, shortest paths: [['118', '601', '309']]
Total paths: 1, num paths: 1
86
df_tmp:  168    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 147, with name:  175 St
Connecting lines: []
From 147 to 118, shortest paths: [['118', '618', '147'], ['118', '621', '147']]
Total paths: 2, num paths: 1
87
df_tmp:  174    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 159, with name:  81 St-Museum of Natural History
Connecting lines: []
From 159 to 118, shortest paths: [['118', '618', '159'], ['118', '621', '159']]
Total paths: 2, num paths: 1
88
df_tmp:  103    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 254, with name:  Jamaica-179 St
Connecting lines: []
From 254 to 118, shortest paths: [['118', '601', '254']]
Total paths: 1, num paths: 1
89
df_tmp:  65    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 613, with name:  59 St
Connecting lines: []
From 613 to 118, shortest paths: [['118', '602', '613']]
Total paths: 1, num paths: 1
90
df_tmp:  7    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 190, with name:  80 St
Connecting lines: []
From 190 to 118, shortest paths: [['118', '618', '190'], ['118', '621', '190']]
Total paths: 2, num paths: 1
91
df_tmp:  66    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 616, with name:  74 St-Broadway
Connecting lines: []
From 616 to 118, shortest paths: [['118', '601', '616'], ['118', '618', '616']]
Total paths: 2, num paths: 2
92
df_tmp:  175    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 134, with name:  Sutter Av
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
134 is not in stops_before
Origin complex id: 100, with name:  Hewes St
Connecting lines: []
From 100 to 118, shortest paths: [['118', '621', '100']]
Total paths: 1, num paths: 0
94
Origin complex id: 191, with name:  88 St
Connecting lines: []
From 191 to 118, shortest paths: [['118', '618', '191'], ['118', '621', '191']]
Total paths: 2, num paths: 1
95
df_tmp:  91    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 328, with name:  WTC Cortlandt
Connecting lines: []
From 328 to 118, shortest paths: [['118', '601', '328']]
Total paths: 1, num paths: 1
96
df_tmp:  67    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 620, with name:  Borough Hall
Connecting lines: []
From 620 to 118, shortest paths: [['118', '602', '620'], ['118', '601', '620']]
Total paths: 2, num paths: 2
97
df_tmp:  15    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 369, with name:  Elder Av
Connecting lines: []
From 369 to 118, shortest paths: [['118', '602', '369']]
Total paths: 1, num paths: 1
98
df_tmp:  117    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 58, with name:  Coney Island-Stillwell Av
Connecting lines: []
From 58 to 118, shortest paths: [['118', '602', '58'], ['118', '601', '58']]
Total paths: 2, num paths: 2
99
df_tmp:  93    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 434, with name:  3 Av-149 St
Connecting lines: []
From 434 to 118, shortest paths: [['118', '601', '434']]
Total paths: 1, num paths: 1
100
df_tmp:  34    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 301, with name:  181 St
Connecting lines: []
From 301 to 118, shortest paths: [['118', '601', '301']]
Total paths: 1, num paths: 1
101
df_tmp:  144    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 90, with name:  Van Siclen Av
Connecting lines: []
From 90 to 118, shortest paths: [['118', '621', '90']]
Total paths: 1, num paths: 0
102
Origin complex id: 381, with name:  Kingsbridge Rd
Connecting lines: []
From 381 to 118, shortest paths: [['118', '602', '381']]
Total paths: 1, num paths: 1
103
df_tmp:  139    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 392, with name:  125 St
Connecting lines: []
From 392 to 118, shortest paths: [['118', '602', '392']]
Total paths: 1, num paths: 1
104
df_tmp:  215    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 154, with name:  116 St
Connecting lines: []
From 154 to 118, shortest paths: [['118', '618', '154'], ['118', '621', '154']]
Total paths: 2, num paths: 1
105
df_tmp:  195    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 187, with name:  Shepherd Av
Connecting lines: []
From 187 to 118, shortest paths: [['118', '618', '187'], ['118', '621', '187']]
Total paths: 2, num paths: 1
106
df_tmp:  59    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 137, with name:  East 105 St
Connecting lines: ['L']
Stops before stop 118: [602, 601, 618]
137 is not in stops_before
Origin complex id: 167, with name:  W 4 St-Wash Sq
Connecting lines: []
From 167 to 118, shortest paths: [['118', '601', '167'], ['118', '618', '167'], ['118', '621', '167']]
Total paths: 3, num paths: 2
108
df_tmp:  199    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 35, with name:  59 St
Connecting lines: []
From 35 to 118, shortest paths: [['118', '602', '35']]
Total paths: 1, num paths: 1
109
df_tmp:  101    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 451, with name:  Junction Blvd
Connecting lines: []
From 451 to 118, shortest paths: [['118', '602', '610', '451'], ['118', '602', '611', '451'], ['118', '601', '611', '451'], ['118', '618', '611', '451'], ['118', '621', '611', '451'], ['118', '602', '461', '451'], ['118', '601', '609', '451'], ['118', '601', '616', '451'], ['118', '618', '616', '451'], ['118', '618', '606', '451'], ['118', '629', '606', '451']]
Total paths: 11, num paths: 9
110
df_tmp:  100    118
Name: destination_station_complex_id, dtype: int64
Origin complex id: 270, with name:  46 St
Connecting lines: []

In [18]:
print("Total Onboardings: ", obs_onboard)

df_onboard.head(15)

Total Onboardings:  65.7372208699902

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,9,Monday,9,118,3 Av (L),120,Bedford Av (L),21.71060
1,2025,9,Monday,9,118,3 Av (L),122,Graham Av (L),5.35300
2,2025,9,Monday,9,118,3 Av (L),164,"34 St-Penn Station (A,C,E)",2.50580
3,2025,9,Monday,9,118,3 Av (L),629,Lorimer St (L)/Metropolitan Av (G),3.75920
4,2025,9,Monday,9,118,3 Av (L),611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",0.78825
5,2025,9,Monday,9,118,3 Av (L),138,Canarsie-Rockaway Pkwy (L),2.62560
6,2025,9,Monday,9,118,3 Av (L),283,Greenpoint Av (G),2.56320
7,2025,9,Monday,9,118,3 Av (L),168,"Spring St (C,E)",1.14320
8,2025,9,Monday,9,118,3 Av (L),127,DeKalb Av (L),2.28160
9,2025,9,Monday,9,118,3 Av (L),129,Halsey St (L),1.44080
10,2025,9,Monday,9,118,3 Av (L),165,"23 St (C,E)",0.68620
11,2025,9,Monday,9,118,3 Av (L),125,Morgan Av (L),1.36480
12,2025,9,Monday,9,118,3 Av (L),126,Jefferson St (L),1.13720
13,2025,9,Monday,9,118,3 Av (L),123,Grand St (L),1.10300
14,2025,9,Monday,9,118,3 Av (L),636,"Jay St-MetroTech (A,C,F,R)",0.25185

In [111]:
print("Total Offboardings: ", obs_offboard)

df_offboard.head(15)

Total Offboardings:  880.678124900392

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,9,Tuesday,9,120,Bedford Av (L),618,"14 St (A,C,E)/8 Av (L)",185.263600
1,2025,9,Tuesday,9,610,"Grand Central-42 St (S,4,5,6,7)",618,"14 St (A,C,E)/8 Av (L)",17.579778
2,2025,9,Tuesday,9,629,Lorimer St (L)/Metropolitan Av (G),618,"14 St (A,C,E)/8 Av (L)",74.554000
3,2025,9,Tuesday,9,119,1 Av (L),618,"14 St (A,C,E)/8 Av (L)",65.635400
4,2025,9,Tuesday,9,630,"Myrtle-Wyckoff Avs (L,M)",618,"14 St (A,C,E)/8 Av (L)",49.203400
5,2025,9,Tuesday,9,122,Graham Av (L),618,"14 St (A,C,E)/8 Av (L)",49.163800
6,2025,9,Tuesday,9,127,DeKalb Av (L),618,"14 St (A,C,E)/8 Av (L)",41.208400
7,2025,9,Tuesday,9,129,Halsey St (L),618,"14 St (A,C,E)/8 Av (L)",30.318200
8,2025,9,Tuesday,9,125,Morgan Av (L),618,"14 St (A,C,E)/8 Av (L)",28.248600
9,2025,9,Tuesday,9,124,Montrose Av (L),618,"14 St (A,C,E)/8 Av (L)",27.230200
10,2025,9,Tuesday,9,283,Greenpoint Av (G),618,"14 St (A,C,E)/8 Av (L)",6.727550
11,2025,9,Tuesday,9,476,86 St (Q),618,"14 St (A,C,E)/8 Av (L)",6.678700
12,2025,9,Tuesday,9,289,Bedford-Nostrand Avs (G),618,"14 St (A,C,E)/8 Av (L)",6.671800
13,2025,9,Tuesday,9,126,Jefferson St (L),618,"14 St (A,C,E)/8 Av (L)",24.649200
14,2025,9,Tuesday,9,477,72 St (Q),618,"14 St (A,C,E)/8 Av (L)",6.111200

In [96]:
stops_on_line = get_ordered_stops(line, direction, 1)
stops_on_line

[618,
 601,
 602,
 118,
 119,
 120,
 629,
 122,
 123,
 124,
 125,
 126,
 127,
 630,
 129,
 130,
 131,
 621,
 133,
 134,
 135,
 136,
 137,
 138]

In [93]:
df_onboards.head(15)

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
37,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",164,"34 St-Penn Station (A,C,E)",89.6797
83,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",276,"5 Av/53 St (E,M)",75.4958
85,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",57.8625
38,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",624,"Chambers St (A,C)/WTC (E)/Park Pl (2,3)/Cortla...",49.6112
198,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",610,"Grand Central-42 St (S,4,5,6,7)",45.9287
183,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",612,"Lexington Av-53 St (E,M)/51 St (6)",44.2830
166,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",168,"Spring St (C,E)",36.6125
72,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",614,"59 St-Columbus Circle (A,B,C,D,1)",32.9348
241,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",169,"Canal St (A,C,E)",31.7987
127,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",628,"Fulton St (A,C,J,Z,2,3,4,5)",27.2395
121,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",277,"7 Av (E,B,D)",27.2020
21,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",225,"47-50 Sts-Rockefeller Ctr (B,D,F,M)",22.2322
134,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",21.3260
112,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",120,Bedford Av (L),18.8100
74,2025,2,Tuesday,9,618,"14 St (A,C,E)/8 Av (L)",609,"Bryant Pk (B,D,F,M)/5 Av (7)",18.0710

In [89]:
df_onboards = get_onboards_data(complex_id, year, month, day_of_week, hour_of_day)
obs, df = get_onboardings (complex_id, line, line, df_onboards)

L
L

IndexError: single positional indexer is out-of-bounds